------------------ This file was auto-generated with 824 entries ------------------
return {
  ["compression"] = {
    all_continuations = {
      "detonation",
      "transfixion",
    },
    ["detonation"] = {
      "Aeolian Edge",
      "Backhand Blow",
      "Blade: Jin",
      "Blade: To",
      "Bora Axe",
      "Cyclone",
      "Dancing Edge",
      "Earth Crusher",
      "Fell Cleave",
      "Fimbulvetr",
      "Freezebite",
      "Gale Axe",
      "Gust Slash",
      "Herculean Slash",
      "Imperator",
      "Maru Kala",
      "Numbing Shot",
      "Raging Axe",
      "Red Lotus Blade",
      "Ruinator",
      "Shell Crusher",
      "Steel Cyclone",
      "Tachi: Jinpu",
      "Tachi: Mumei",
      "Tachi: Yukikaze",
      "Tornado Kick",
      "True Strike",
    },
    ["transfixion"] = {
      "Apex Arrow",
      "Ascetic's Fury",
      "Blade: Chi",
      "Blade: Ku",
      "Blade: Rin",
      "Blast Arrow",
      "Blast Shot",
      "Dagda",
      "Detonator",
      "Diarmuid",
      "Disaster",
      "Double Thrust",
      "Drakesbane",
      "Dulling Arrow",
      "Empyreal Arrow",
      "Evisceration",
      "Flaming Arrow",
      "Hot Shot",
      "Howling Fist",
      "Leaden Salute",
      "Omniscience",
      "Piercing Arrow",
      "Power Slash",
      "Raiden Thrust",
      "Refulgent Arrow",
      "Sarv",
      "Sidewinder",
      "Skewer",
      "Slug Shot",
      "Sniper Shot",
      "Sonic Thrust",
      "Split Shot",
      "Stardiver",
      "Tachi: Enpi",
      "Tachi: Goten",
      "Thunder Thrust",
      "Vorpal Scythe",
      "Vorpal Thrust",
    },
  },
  ["detonation"] = {
    all_continuations = {
      "gravitation",
      "scission",
    },
    ["gravitation"] = {
      "Black Halo",
      "Blade: Ei",
      "Blade: Kamu",
      "Cataclysm",
      "Fimbulvetr",
      "Imperator",
      "Infernal Scythe",
      "Insurgency",
      "Keen Edge",
      "Mandalic Stab",
      "Maru Kala",
      "Nightmare Scythe",
      "One Inch Punch",
      "Penta Thrust",
      "Starburst",
      "Sunburst",
      "Tachi: Ageha",
      "Tachi: Kasha",
      "Tachi: Mumei",
      "Tachi: Shoha",
      "Upheaval",
    },
    ["scission"] = {
      "Aeolian Edge",
      "Avalanche Axe",
      "Blade: Retsu",
      "Blade: Yu",
      "Bora Axe",
      "Calamity",
      "Crescent Moon",
      "Dagda",
      "Dancing Edge",
      "Diarmuid",
      "Disaster",
      "Exenterator",
      "Expiacion",
      "Fast Blade",
      "Fell Cleave",
      "Hard Slash",
      "Iron Tempest",
      "King's Justice",
      "Pyrrhic Kleos",
      "Rampage",
      "Requiescat",
      "Resolution",
      "Sarv",
      "Savage Blade",
      "Seraph Blade",
      "Shining Blade",
      "Sickle Moon",
      "Slice",
      "Sonic Thrust",
      "Spinning Axe",
      "Spinning Scythe",
      "Spiral Hell",
      "Sturmwind",
      "Tachi: Enpi",
      "Tachi: Jinpu",
      "Trueflight",
      "Viper Bite",
      "Vorpal Blade",
      "Vorpal Scythe",
      "Wasp Sting",
    },
  },
  ["impaction"] = {
    all_continuations = {
      "detonation",
      "liquefaction",
    },
    ["detonation"] = {
      "Aeolian Edge",
      "Backhand Blow",
      "Blade: Jin",
      "Blade: To",
      "Bora Axe",
      "Cyclone",
      "Dancing Edge",
      "Earth Crusher",
      "Fell Cleave",
      "Fimbulvetr",
      "Freezebite",
      "Gale Axe",
      "Gust Slash",
      "Herculean Slash",
      "Imperator",
      "Maru Kala",
      "Numbing Shot",
      "Raging Axe",
      "Ruinator",
      "Shell Crusher",
      "Sidewinder",
      "Slug Shot",
      "Steel Cyclone",
      "Tachi: Jinpu",
      "Tachi: Mumei",
      "Tachi: Yukikaze",
      "Tornado Kick",
      "True Strike",
    },
    ["liquefaction"] = {
      "Asuran Fists",
      "Blitz",
      "Burning Blade",
      "Dulling Arrow",
      "Flaming Arrow",
      "Full Swing",
      "Red Lotus Blade",
      "Ruthless Stroke",
      "Sniper Shot",
      "Spinning Attack",
      "Spinning Axe",
      "Stringing Pummel",
      "Tachi: Kagero",
    },
  },
  ["induration"] = {
    all_continuations = {
      "compression",
      "fragmentation",
      "impaction",
    },
    ["compression"] = {
      "Black Halo",
      "Blade: Ei",
      "Blade: Kamu",
      "Cataclysm",
      "Fimbulvetr",
      "Imperator",
      "Infernal Scythe",
      "Insurgency",
      "Keen Edge",
      "Mandalic Stab",
      "Maru Kala",
      "Nightmare Scythe",
      "One Inch Punch",
      "Penta Thrust",
      "Starburst",
      "Sunburst",
      "Tachi: Ageha",
      "Tachi: Kasha",
      "Tachi: Mumei",
      "Tachi: Shoha",
      "Upheaval",
    },
    ["fragmentation"] = {
      "Atonement",
      "Blade: Teki",
      "Blade: Yu",
      "Brainshaker",
      "Circle Blade",
      "Dark Harvest",
      "Decimation",
      "Entropy",
      "Flash Nova",
      "Garland of Bliss",
      "Hot Shot",
      "Last Stand",
      "Origin",
      "Oshala",
      "Piercing Arrow",
      "Primal Rend",
      "Raging Rush",
      "Refulgent Arrow",
      "Retribution",
      "Shadow of Death",
      "Shadowstitch",
      "Shijin Spiral",
      "Shockwave",
      "Sidewinder",
      "Skullbreaker",
      "Slug Shot",
      "Spinning Scythe",
      "Split Shot",
      "Sturmwind",
      "Tachi: Gekko",
      "Tachi: Koki",
      "Terminus",
      "Vorpal Thrust",
      "Zesho Meppo",
    },
    ["impaction"] = {
      "Aeolian Edge",
      "Armor Break",
      "Avalanche Axe",
      "Blade: Chi",
      "Blade: Jin",
      "Blade: Shun",
      "Blitz",
      "Calamity",
      "Combo",
      "Cyclone",
      "Earth Crusher",
      "Flat Blade",
      "Full Swing",
      "Heavy Swing",
      "Herculean Slash",
      "Howling Fist",
      "Judgment",
      "Leg Sweep",
      "Numbing Shot",
      "Raging Axe",
      "Raging Fists",
      "Raiden Thrust",
      "Realmrazer",
      "Rock Crusher",
      "Ruthless Stroke",
      "Seraph Strike",
      "Shield Break",
      "Shining Strike",
      "Shoulder Tackle",
      "Sickle Moon",
      "Skewer",
      "Smash Axe",
      "Spinning Attack",
      "Spinning Axe",
      "Tachi: Goten",
      "Thunder Thrust",
      "Tornado Kick",
      "True Strike",
      "Vorpal Blade",
      "Weapon Break",
    },
  },
  ["liquefaction"] = {
    all_continuations = {
      "fusion",
      "scission",
    },
    ["fusion"] = {
      "Armor Break",
      "Blade: Chi",
      "Blade: Jin",
      "Blade: Shun",
      "Blitz",
      "Circle Blade",
      "Combo",
      "Cyclone",
      "Earth Crusher",
      "Flat Blade",
      "Full Swing",
      "Heavy Swing",
      "Herculean Slash",
      "Howling Fist",
      "Judgment",
      "Leg Sweep",
      "Numbing Shot",
      "Raging Axe",
      "Raging Fists",
      "Raiden Thrust",
      "Realmrazer",
      "Rock Crusher",
      "Ruthless Stroke",
      "Seraph Strike",
      "Shield Break",
      "Shining Strike",
      "Shoulder Tackle",
      "Skewer",
      "Smash Axe",
      "Spinning Attack",
      "Tachi: Goten",
      "Tachi: Koki",
      "Thunder Thrust",
      "Tornado Kick",
      "True Strike",
      "Weapon Break",
    },
    ["scission"] = {
      "Aeolian Edge",
      "Avalanche Axe",
      "Blade: Retsu",
      "Blade: Yu",
      "Bora Axe",
      "Calamity",
      "Crescent Moon",
      "Dagda",
      "Dancing Edge",
      "Diarmuid",
      "Disaster",
      "Exenterator",
      "Expiacion",
      "Fast Blade",
      "Fell Cleave",
      "Hard Slash",
      "Iron Tempest",
      "King's Justice",
      "Nightmare Scythe",
      "Pyrrhic Kleos",
      "Rampage",
      "Requiescat",
      "Resolution",
      "Sarv",
      "Savage Blade",
      "Seraph Blade",
      "Shining Blade",
      "Sickle Moon",
      "Slice",
      "Sonic Thrust",
      "Spinning Axe",
      "Spinning Scythe",
      "Spiral Hell",
      "Sturmwind",
      "Tachi: Ageha",
      "Tachi: Enpi",
      "Tachi: Jinpu",
      "Trueflight",
      "Viper Bite",
      "Vorpal Blade",
      "Vorpal Scythe",
      "Wasp Sting",
    },
  },
  ["reverberation"] = {
    all_continuations = {
      "impaction",
      "induration",
    },
    ["impaction"] = {
      "Aeolian Edge",
      "Armor Break",
      "Avalanche Axe",
      "Blade: Chi",
      "Blade: Jin",
      "Blade: Shun",
      "Blitz",
      "Calamity",
      "Circle Blade",
      "Combo",
      "Cyclone",
      "Earth Crusher",
      "Flat Blade",
      "Full Swing",
      "Heavy Swing",
      "Howling Fist",
      "Judgment",
      "Leg Sweep",
      "Raging Axe",
      "Raging Fists",
      "Raiden Thrust",
      "Realmrazer",
      "Rock Crusher",
      "Ruthless Stroke",
      "Seraph Strike",
      "Shield Break",
      "Shining Strike",
      "Shoulder Tackle",
      "Sickle Moon",
      "Skewer",
      "Smash Axe",
      "Spinning Attack",
      "Spinning Axe",
      "Tachi: Goten",
      "Tachi: Koki",
      "Thunder Thrust",
      "True Strike",
      "Vorpal Blade",
      "Weapon Break",
    },
    ["induration"] = {
      "Blade: To",
      "Blast Arrow",
      "Blast Shot",
      "Flash Nova",
      "Freezebite",
      "Frostbite",
      "Guillotine",
      "Herculean Slash",
      "Impulse Drive",
      "Numbing Shot",
      "Origin",
      "Oshala",
      "Raging Rush",
      "Shadow of Death",
      "Shattersoul",
      "Skullbreaker",
      "Tachi: Hobaku",
      "Tachi: Rana",
      "Tachi: Yukikaze",
      "Terminus",
      "Tornado Kick",
      "Zesho Meppo",
    },
  },
  ["scission"] = {
    all_continuations = {
      "detonation",
      "liquefaction",
      "reverberation",
    },
    ["detonation"] = {
      "Aeolian Edge",
      "Backhand Blow",
      "Blade: Jin",
      "Blade: To",
      "Bora Axe",
      "Cyclone",
      "Dancing Edge",
      "Earth Crusher",
      "Fell Cleave",
      "Fimbulvetr",
      "Freezebite",
      "Gale Axe",
      "Gust Slash",
      "Herculean Slash",
      "Imperator",
      "Maru Kala",
      "Numbing Shot",
      "Raging Axe",
      "Ruinator",
      "Shell Crusher",
      "Steel Cyclone",
      "Tachi: Jinpu",
      "Tachi: Mumei",
      "Tachi: Yukikaze",
      "Tornado Kick",
      "True Strike",
    },
    ["liquefaction"] = {
      "Asuran Fists",
      "Blitz",
      "Burning Blade",
      "Dulling Arrow",
      "Flaming Arrow",
      "Full Swing",
      "Red Lotus Blade",
      "Ruthless Stroke",
      "Sniper Shot",
      "Spinning Attack",
      "Spinning Axe",
      "Stringing Pummel",
      "Tachi: Kagero",
    },
    ["reverberation"] = {
      "Atonement",
      "Blade: Teki",
      "Blade: Yu",
      "Brainshaker",
      "Cataclysm",
      "Circle Blade",
      "Dark Harvest",
      "Decimation",
      "Entropy",
      "Flash Nova",
      "Garland of Bliss",
      "Hot Shot",
      "Infernal Scythe",
      "Last Stand",
      "Origin",
      "Oshala",
      "Piercing Arrow",
      "Primal Rend",
      "Raging Rush",
      "Refulgent Arrow",
      "Retribution",
      "Shadow of Death",
      "Shadowstitch",
      "Shijin Spiral",
      "Shockwave",
      "Shoulder Tackle",
      "Sidewinder",
      "Skullbreaker",
      "Slug Shot",
      "Smash Axe",
      "Spinning Scythe",
      "Split Shot",
      "Starburst",
      "Sturmwind",
      "Sunburst",
      "Tachi: Gekko",
      "Tachi: Koki",
      "Terminus",
      "Vorpal Thrust",
      "Zesho Meppo",
    },
  },
  ["transfixion"] = {
    all_continuations = {
      "compression",
      "distortion",
      "reverberation",
    },
    ["compression"] = {
      "Black Halo",
      "Blade: Ei",
      "Blade: Kamu",
      "Cataclysm",
      "Fimbulvetr",
      "Imperator",
      "Infernal Scythe",
      "Insurgency",
      "Keen Edge",
      "Mandalic Stab",
      "Maru Kala",
      "Nightmare Scythe",
      "One Inch Punch",
      "Penta Thrust",
      "Starburst",
      "Sunburst",
      "Tachi: Ageha",
      "Tachi: Kasha",
      "Tachi: Mumei",
      "Tachi: Shoha",
      "Upheaval",
    },
    ["distortion"] = {
      "Aeolian Edge",
      "Avalanche Axe",
      "Blade: Retsu",
      "Bora Axe",
      "Calamity",
      "Crescent Moon",
      "Dagda",
      "Dancing Edge",
      "Diarmuid",
      "Disaster",
      "Exenterator",
      "Expiacion",
      "Fast Blade",
      "Fell Cleave",
      "Hard Slash",
      "Iron Tempest",
      "King's Justice",
      "Pyrrhic Kleos",
      "Rampage",
      "Requiescat",
      "Resolution",
      "Sarv",
      "Savage Blade",
      "Seraph Blade",
      "Shining Blade",
      "Sickle Moon",
      "Slice",
      "Sonic Thrust",
      "Spinning Axe",
      "Spiral Hell",
      "Tachi: Enpi",
      "Tachi: Jinpu",
      "Trueflight",
      "Viper Bite",
      "Vorpal Blade",
      "Vorpal Scythe",
      "Wasp Sting",
    },
    ["reverberation"] = {
      "Atonement",
      "Blade: Teki",
      "Blade: Yu",
      "Brainshaker",
      "Circle Blade",
      "Dark Harvest",
      "Decimation",
      "Entropy",
      "Flash Nova",
      "Garland of Bliss",
      "Hot Shot",
      "Last Stand",
      "Origin",
      "Oshala",
      "Piercing Arrow",
      "Primal Rend",
      "Raging Rush",
      "Refulgent Arrow",
      "Retribution",
      "Shadow of Death",
      "Shadowstitch",
      "Shijin Spiral",
      "Shockwave",
      "Shoulder Tackle",
      "Sidewinder",
      "Skullbreaker",
      "Slug Shot",
      "Smash Axe",
      "Spinning Scythe",
      "Split Shot",
      "Sturmwind",
      "Tachi: Gekko",
      "Tachi: Koki",
      "Terminus",
      "Vorpal Thrust",
      "Zesho Meppo",
    },
  },
  ["distortion"] = {
    all_continuations = {
      "darkness",
      "fusion",
    },
    ["darkness"] = {
      "Asuran Fists",
      "Blade: Hi",
      "Blade: Ku",
      "Blade: Ten",
      "Catastrophe",
      "Dagda",
      "Diarmuid",
      "Disaster",
      "Entropy",
      "Evisceration",
      "Impulse Drive",
      "Leaden Salute",
      "Mercy Stroke",
      "Omniscience",
      "Onslaught",
      "Primal Rend",
      "Requiescat",
      "Retribution",
      "Sarv",
      "Shattersoul",
      "Stardiver",
      "Stringing Pummel",
      "Swift Blade",
      "Tachi: Rana",
      "Wildfire",
    },
    ["fusion"] = {
      "Arching Arrow",
      "Ascetic's Fury",
      "Atonement",
      "Blade: Shun",
      "Decimation",
      "Detonator",
      "Drakesbane",
      "Empyreal Arrow",
      "Fast Blade II",
      "Final Heaven",
      "Garland of Bliss",
      "Glory Slash",
      "Heavy Shot",
      "Hexa Strike",
      "Insurgency",
      "Jishnu's Radiance",
      "Knights of Round",
      "Last Stand",
      "Mandalic Stab",
      "Metatron Torment",
      "Mistral Axe",
      "Origin",
      "Oshala",
      "Realmrazer",
      "Scourge",
      "Shijin Spiral",
      "Tachi: Kasha",
      "Tachi: Suikawari",
      "Terminus",
      "Upheaval",
      "Wheeling Thrust",
      "Zesho Meppo",
    },
  },
  ["fragmentation"] = {
    all_continuations = {
      "distortion",
      "light",
    },
    ["distortion"] = {
      "Chant du Cygne",
      "Cross Reaper",
      "Death Blossom",
      "Dragon Blow",
      "Expiacion",
      "Fimbulvetr",
      "Full Break",
      "Gate of Tartarus",
      "Geirskogul",
      "Ground Strike",
      "Imperator",
      "Maru Kala",
      "Mordant Rime",
      "Namas Arrow",
      "Pyrrhic Kleos",
      "Quietus",
      "Rudra's Storm",
      "Ruinator",
      "Spiral Hell",
      "Steel Cyclone",
      "Tachi: Fudo",
      "Tachi: Gekko",
      "Tachi: Mumei",
      "Torcleaver",
      "Vidohunir",
    },
    ["light"] = {
      "Arching Arrow",
      "Ascetic's Fury",
      "Atonement",
      "Blade: Shun",
      "Decimation",
      "Detonator",
      "Drakesbane",
      "Empyreal Arrow",
      "Fast Blade II",
      "Final Heaven",
      "Garland of Bliss",
      "Glory Slash",
      "Heavy Shot",
      "Hexa Strike",
      "Insurgency",
      "Jishnu's Radiance",
      "Knights of Round",
      "Last Stand",
      "Mandalic Stab",
      "Metatron Torment",
      "Mistral Axe",
      "Origin",
      "Oshala",
      "Realmrazer",
      "Scourge",
      "Shijin Spiral",
      "Tachi: Kasha",
      "Tachi: Suikawari",
      "Terminus",
      "Upheaval",
      "Wheeling Thrust",
      "Zesho Meppo",
    },
  },
  ["fusion"] = {
    all_continuations = {
      "gravitation",
      "light",
    },
    ["gravitation"] = {
      "Asuran Fists",
      "Blade: Hi",
      "Blade: Ku",
      "Blade: Ten",
      "Catastrophe",
      "Dagda",
      "Diarmuid",
      "Disaster",
      "Entropy",
      "Evisceration",
      "Impulse Drive",
      "Leaden Salute",
      "Mercy Stroke",
      "Omniscience",
      "Onslaught",
      "Primal Rend",
      "Requiescat",
      "Retribution",
      "Sarv",
      "Shattersoul",
      "Stardiver",
      "Stringing Pummel",
      "Swift Blade",
      "Tachi: Rana",
      "Wildfire",
    },
    ["light"] = {
      "Apex Arrow",
      "Black Halo",
      "Blade: Kamu",
      "Blade: Metsu",
      "Blitz",
      "Camlann's Torment",
      "Cloudsplitter",
      "Coronach",
      "Death Blossom",
      "Dimidiation",
      "Dragon Kick",
      "Exenterator",
      "Exudation",
      "Ground Strike",
      "King's Justice",
      "Mordant Rime",
      "Randgrith",
      "Resolution",
      "Ruthless Stroke",
      "Savage Blade",
      "Shark Bite",
      "Spinning Slash",
      "Tachi: Kaiten",
      "Tachi: Shoha",
      "Trueflight",
      "Ukko's Fury",
      "Uriel Blade",
      "Victory Smite",
      "Vidohunir",
    },
  },
  ["gravitation"] = {
    all_continuations = {
      "darkness",
      "fragmentation",
    },
    ["darkness"] = {
      "Chant du Cygne",
      "Cross Reaper",
      "Dragon Blow",
      "Expiacion",
      "Fimbulvetr",
      "Full Break",
      "Gate of Tartarus",
      "Geirskogul",
      "Imperator",
      "Maru Kala",
      "Namas Arrow",
      "Pyrrhic Kleos",
      "Quietus",
      "Rudra's Storm",
      "Ruinator",
      "Spiral Hell",
      "Steel Cyclone",
      "Tachi: Fudo",
      "Tachi: Gekko",
      "Tachi: Mumei",
      "Torcleaver",
    },
    ["fragmentation"] = {
      "Apex Arrow",
      "Black Halo",
      "Blade: Kamu",
      "Blade: Metsu",
      "Blitz",
      "Camlann's Torment",
      "Cloudsplitter",
      "Coronach",
      "Death Blossom",
      "Dimidiation",
      "Dragon Kick",
      "Exenterator",
      "Exudation",
      "Ground Strike",
      "King's Justice",
      "Mordant Rime",
      "Randgrith",
      "Resolution",
      "Ruthless Stroke",
      "Savage Blade",
      "Shark Bite",
      "Spinning Slash",
      "Tachi: Kaiten",
      "Tachi: Shoha",
      "Trueflight",
      "Ukko's Fury",
      "Uriel Blade",
      "Victory Smite",
      "Vidohunir",
    },
  },
  ["darkness"] = {
    all_continuations = {
      "darkness ii",
    },
    ["darkness ii"] = {
      "Blade: Hi",
      "Blade: Metsu",
      "Catastrophe",
      "Cloudsplitter",
      "Coronach",
      "Exudation",
      "Gate of Tartarus",
      "Mercy Stroke",
      "Onslaught",
      "Quietus",
      "Rudra's Storm",
      "Wildfire",
    },
  },
  ["light"] = {
    all_continuations = {
      "light ii",
    },
    ["light ii"] = {
      "Camlann's Torment",
      "Chant du Cygne",
      "Dimidiation",
      "Final Heaven",
      "Final Paradise",
      "Geirskogul",
      "Glory Slash",
      "Jishnu's Radiance",
      "Knights of Rotund",
      "Knights of Round",
      "Metatron Torment",
      "Namas Arrow",
      "Randgrith",
      "Scourge",
      "Tachi: Fudo",
      "Tachi: Kaiten",
      "Torcleaver",
      "Ukko's Fury",
      "Uriel Blade",
      "Victory Smite",
    },
  },
  ["darkness ii"] = {
    all_continuations = {
    },
  },
  ["light ii"] = {
    all_continuations = {
    },
  },
}
