------------------ This file was auto-generated with 20372 entries ------------------
return {
  ["compression"] = {
    all_openers = {
      "apex arrow",
      "ascetic's fury",
      "blade: chi",
      "blade: ku",
      "blade: rin",
      "blade: to",
      "blast arrow",
      "blast shot",
      "dagda",
      "detonator",
      "diarmuid",
      "disaster",
      "double thrust",
      "drakesbane",
      "dulling arrow",
      "empyreal arrow",
      "evisceration",
      "flaming arrow",
      "flash nova",
      "freezebite",
      "frostbite",
      "guillotine",
      "herculean slash",
      "hot shot",
      "howling fist",
      "impulse drive",
      "leaden salute",
      "numbing shot",
      "omniscience",
      "origin",
      "oshala",
      "piercing arrow",
      "power slash",
      "raging rush",
      "raiden thrust",
      "refulgent arrow",
      "sarv",
      "shadow of death",
      "shattersoul",
      "sidewinder",
      "skewer",
      "skullbreaker",
      "slug shot",
      "sniper shot",
      "sonic thrust",
      "split shot",
      "stardiver",
      "tachi: enpi",
      "tachi: goten",
      "tachi: hobaku",
      "tachi: rana",
      "tachi: yukikaze",
      "terminus",
      "thunder thrust",
      "tornado kick",
      "vorpal scythe",
      "vorpal thrust",
      "zesho meppo",
    },
    groupings = {
      {
        open_with = {
          "ascetic's fury",
          "blade: chi",
          "blade: ku",
          "blade: rin",
          "blade: to",
          "blast arrow",
          "blast shot",
          "dagda",
          "detonator",
          "diarmuid",
          "disaster",
          "double thrust",
          "drakesbane",
          "dulling arrow",
          "empyreal arrow",
          "evisceration",
          "flaming arrow",
          "flash nova",
          "freezebite",
          "frostbite",
          "guillotine",
          "herculean slash",
          "hot shot",
          "howling fist",
          "impulse drive",
          "leaden salute",
          "numbing shot",
          "omniscience",
          "origin",
          "oshala",
          "piercing arrow",
          "power slash",
          "raging rush",
          "raiden thrust",
          "refulgent arrow",
          "sarv",
          "shadow of death",
          "shattersoul",
          "sidewinder",
          "skewer",
          "skullbreaker",
          "slug shot",
          "sniper shot",
          "sonic thrust",
          "split shot",
          "stardiver",
          "tachi: enpi",
          "tachi: goten",
          "tachi: hobaku",
          "tachi: rana",
          "tachi: yukikaze",
          "terminus",
          "thunder thrust",
          "tornado kick",
          "vorpal scythe",
          "vorpal thrust",
          "zesho meppo",
        },
        close_with = {
          "black halo",
          "blade: ei",
          "blade: kamu",
          "cataclysm",
          "fimbulvetr",
          "imperator",
          "infernal scythe",
          "insurgency",
          "keen edge",
          "mandalic stab",
          "maru kala",
          "nightmare scythe",
          "one inch punch",
          "penta thrust",
          "starburst",
          "sunburst",
          "tachi: ageha",
          "tachi: kasha",
          "tachi: mumei",
          "tachi: shoha",
          "upheaval",
        },
      },
      {
        open_with = {
          "apex arrow",
        },
        close_with = {
          "black halo",
          "blade: ei",
          "blade: kamu",
          "cataclysm",
          "infernal scythe",
          "keen edge",
          "nightmare scythe",
          "one inch punch",
          "penta thrust",
          "starburst",
          "sunburst",
          "tachi: ageha",
          "tachi: shoha",
        },
      },
    },
  },
  ["detonation"] = {
    all_openers = {
      "aeolian edge",
      "armor break",
      "avalanche axe",
      "black halo",
      "blade: chi",
      "blade: ei",
      "blade: jin",
      "blade: kamu",
      "blade: retsu",
      "blade: shun",
      "blade: yu",
      "blitz",
      "bora axe",
      "calamity",
      "cataclysm",
      "circle blade",
      "combo",
      "crescent moon",
      "cyclone",
      "dagda",
      "dancing edge",
      "diarmuid",
      "disaster",
      "earth crusher",
      "exenterator",
      "expiacion",
      "fast blade",
      "fell cleave",
      "fimbulvetr",
      "flat blade",
      "full swing",
      "hard slash",
      "heavy swing",
      "herculean slash",
      "howling fist",
      "imperator",
      "infernal scythe",
      "insurgency",
      "iron tempest",
      "judgment",
      "keen edge",
      "king's justice",
      "leg sweep",
      "mandalic stab",
      "maru kala",
      "nightmare scythe",
      "numbing shot",
      "one inch punch",
      "penta thrust",
      "pyrrhic kleos",
      "raging axe",
      "raging fists",
      "raiden thrust",
      "rampage",
      "realmrazer",
      "requiescat",
      "resolution",
      "rock crusher",
      "ruthless stroke",
      "sarv",
      "savage blade",
      "seraph blade",
      "seraph strike",
      "shield break",
      "shining blade",
      "shining strike",
      "shoulder tackle",
      "sickle moon",
      "skewer",
      "slice",
      "smash axe",
      "sonic thrust",
      "spinning attack",
      "spinning axe",
      "spinning scythe",
      "spiral hell",
      "starburst",
      "sturmwind",
      "sunburst",
      "tachi: ageha",
      "tachi: enpi",
      "tachi: goten",
      "tachi: jinpu",
      "tachi: kasha",
      "tachi: koki",
      "tachi: mumei",
      "tachi: shoha",
      "thunder thrust",
      "tornado kick",
      "true strike",
      "trueflight",
      "upheaval",
      "viper bite",
      "vorpal blade",
      "vorpal scythe",
      "wasp sting",
      "weapon break",
    },
    groupings = {
      {
        open_with = {
          "blitz",
          "full swing",
          "herculean slash",
          "numbing shot",
          "ruthless stroke",
          "spinning attack",
          "spinning axe",
          "tornado kick",
        },
        close_with = {
          "backhand blow",
          "blade: to",
          "bora axe",
          "dancing edge",
          "fell cleave",
          "freezebite",
          "gale axe",
          "gust slash",
          "ruinator",
          "shell crusher",
          "steel cyclone",
          "tachi: jinpu",
          "tachi: yukikaze",
        },
      },
      {
        open_with = {
          "aeolian edge",
          "armor break",
          "avalanche axe",
          "black halo",
          "blade: chi",
          "blade: ei",
          "blade: jin",
          "blade: kamu",
          "blade: retsu",
          "blade: shun",
          "bora axe",
          "calamity",
          "cataclysm",
          "combo",
          "crescent moon",
          "cyclone",
          "dagda",
          "dancing edge",
          "diarmuid",
          "disaster",
          "earth crusher",
          "exenterator",
          "expiacion",
          "fast blade",
          "fell cleave",
          "fimbulvetr",
          "flat blade",
          "hard slash",
          "heavy swing",
          "howling fist",
          "imperator",
          "infernal scythe",
          "insurgency",
          "iron tempest",
          "judgment",
          "keen edge",
          "king's justice",
          "leg sweep",
          "mandalic stab",
          "maru kala",
          "nightmare scythe",
          "one inch punch",
          "penta thrust",
          "pyrrhic kleos",
          "raging axe",
          "raging fists",
          "raiden thrust",
          "rampage",
          "realmrazer",
          "requiescat",
          "resolution",
          "rock crusher",
          "sarv",
          "savage blade",
          "seraph blade",
          "seraph strike",
          "shield break",
          "shining blade",
          "shining strike",
          "shoulder tackle",
          "sickle moon",
          "skewer",
          "slice",
          "smash axe",
          "sonic thrust",
          "spiral hell",
          "starburst",
          "sunburst",
          "tachi: ageha",
          "tachi: enpi",
          "tachi: goten",
          "tachi: jinpu",
          "tachi: kasha",
          "tachi: mumei",
          "tachi: shoha",
          "thunder thrust",
          "true strike",
          "trueflight",
          "upheaval",
          "viper bite",
          "vorpal blade",
          "vorpal scythe",
          "wasp sting",
          "weapon break",
        },
        close_with = {
          "aeolian edge",
          "backhand blow",
          "blade: jin",
          "blade: to",
          "bora axe",
          "cyclone",
          "dancing edge",
          "earth crusher",
          "fell cleave",
          "fimbulvetr",
          "freezebite",
          "gale axe",
          "gust slash",
          "herculean slash",
          "imperator",
          "maru kala",
          "numbing shot",
          "raging axe",
          "ruinator",
          "shell crusher",
          "sidewinder",
          "slug shot",
          "steel cyclone",
          "tachi: jinpu",
          "tachi: mumei",
          "tachi: yukikaze",
          "tornado kick",
          "true strike",
        },
      },
      {
        open_with = {
          "blade: yu",
          "circle blade",
          "spinning scythe",
          "sturmwind",
          "tachi: koki",
        },
        close_with = {
          "backhand blow",
          "bora axe",
          "dancing edge",
          "fell cleave",
          "fimbulvetr",
          "gale axe",
          "gust slash",
          "imperator",
          "maru kala",
          "ruinator",
          "shell crusher",
          "steel cyclone",
          "tachi: jinpu",
          "tachi: mumei",
        },
      },
    },
  },
  ["impaction"] = {
    all_openers = {
      "atonement",
      "blade: teki",
      "blade: to",
      "blade: yu",
      "blast arrow",
      "blast shot",
      "brainshaker",
      "cataclysm",
      "circle blade",
      "dark harvest",
      "decimation",
      "entropy",
      "flash nova",
      "freezebite",
      "frostbite",
      "garland of bliss",
      "guillotine",
      "herculean slash",
      "hot shot",
      "impulse drive",
      "infernal scythe",
      "last stand",
      "numbing shot",
      "origin",
      "oshala",
      "piercing arrow",
      "primal rend",
      "raging rush",
      "refulgent arrow",
      "retribution",
      "shadow of death",
      "shadowstitch",
      "shattersoul",
      "shijin spiral",
      "shockwave",
      "shoulder tackle",
      "sidewinder",
      "skullbreaker",
      "slug shot",
      "smash axe",
      "spinning scythe",
      "split shot",
      "starburst",
      "sturmwind",
      "sunburst",
      "tachi: gekko",
      "tachi: hobaku",
      "tachi: koki",
      "tachi: rana",
      "tachi: yukikaze",
      "terminus",
      "tornado kick",
      "vorpal thrust",
      "zesho meppo",
    },
    groupings = {
      {
        open_with = {
          "atonement",
          "blade: teki",
          "blade: to",
          "blade: yu",
          "blast arrow",
          "blast shot",
          "brainshaker",
          "cataclysm",
          "circle blade",
          "dark harvest",
          "decimation",
          "entropy",
          "flash nova",
          "freezebite",
          "frostbite",
          "garland of bliss",
          "guillotine",
          "herculean slash",
          "hot shot",
          "impulse drive",
          "infernal scythe",
          "last stand",
          "numbing shot",
          "origin",
          "oshala",
          "piercing arrow",
          "primal rend",
          "raging rush",
          "refulgent arrow",
          "retribution",
          "shadow of death",
          "shadowstitch",
          "shattersoul",
          "shijin spiral",
          "shockwave",
          "shoulder tackle",
          "sidewinder",
          "skullbreaker",
          "slug shot",
          "smash axe",
          "spinning scythe",
          "split shot",
          "starburst",
          "sturmwind",
          "sunburst",
          "tachi: gekko",
          "tachi: hobaku",
          "tachi: koki",
          "tachi: rana",
          "tachi: yukikaze",
          "terminus",
          "tornado kick",
          "vorpal thrust",
          "zesho meppo",
        },
        close_with = {
          "armor break",
          "avalanche axe",
          "blade: shun",
          "blitz",
          "calamity",
          "circle blade",
          "combo",
          "flat blade",
          "full swing",
          "heavy swing",
          "judgment",
          "leg sweep",
          "raging fists",
          "realmrazer",
          "rock crusher",
          "ruthless stroke",
          "seraph strike",
          "shield break",
          "shining strike",
          "shoulder tackle",
          "sickle moon",
          "smash axe",
          "spinning attack",
          "spinning axe",
          "tachi: koki",
          "vorpal blade",
          "weapon break",
        },
      },
    },
  },
  ["induration"] = {
    all_openers = {
      "atonement",
      "blade: teki",
      "blade: yu",
      "brainshaker",
      "cataclysm",
      "circle blade",
      "dark harvest",
      "decimation",
      "entropy",
      "flash nova",
      "garland of bliss",
      "hot shot",
      "infernal scythe",
      "last stand",
      "origin",
      "oshala",
      "piercing arrow",
      "primal rend",
      "raging rush",
      "refulgent arrow",
      "retribution",
      "shadow of death",
      "shadowstitch",
      "shijin spiral",
      "shockwave",
      "shoulder tackle",
      "sidewinder",
      "skullbreaker",
      "slug shot",
      "smash axe",
      "spinning scythe",
      "split shot",
      "starburst",
      "sturmwind",
      "sunburst",
      "tachi: gekko",
      "tachi: koki",
      "terminus",
      "vorpal thrust",
      "zesho meppo",
    },
    groupings = {
      {
        open_with = {
          "flash nova",
          "origin",
          "oshala",
          "raging rush",
          "shadow of death",
          "skullbreaker",
          "terminus",
          "zesho meppo",
        },
        close_with = {
          "blade: to",
          "blast arrow",
          "blast shot",
          "freezebite",
          "frostbite",
          "guillotine",
          "impulse drive",
          "shattersoul",
          "tachi: hobaku",
          "tachi: rana",
          "tachi: yukikaze",
        },
      },
      {
        open_with = {
          "tachi: gekko",
        },
        close_with = {
          "blade: to",
          "blast arrow",
          "blast shot",
          "flash nova",
          "freezebite",
          "frostbite",
          "guillotine",
          "herculean slash",
          "numbing shot",
          "raging rush",
          "shadow of death",
          "skullbreaker",
          "tachi: hobaku",
          "tachi: yukikaze",
          "tornado kick",
        },
      },
      {
        open_with = {
          "atonement",
          "blade: teki",
          "blade: yu",
          "brainshaker",
          "cataclysm",
          "circle blade",
          "dark harvest",
          "decimation",
          "entropy",
          "garland of bliss",
          "hot shot",
          "infernal scythe",
          "last stand",
          "piercing arrow",
          "primal rend",
          "refulgent arrow",
          "retribution",
          "shadowstitch",
          "shijin spiral",
          "shockwave",
          "shoulder tackle",
          "sidewinder",
          "slug shot",
          "smash axe",
          "spinning scythe",
          "split shot",
          "starburst",
          "sturmwind",
          "sunburst",
          "tachi: koki",
          "vorpal thrust",
        },
        close_with = {
          "flash nova",
          "frostbite",
          "guillotine",
          "impulse drive",
          "origin",
          "oshala",
          "raging rush",
          "shadow of death",
          "shattersoul",
          "skullbreaker",
          "tachi: hobaku",
          "tachi: rana",
          "terminus",
          "zesho meppo",
        },
      },
    },
  },
  ["liquefaction"] = {
    all_openers = {
      "aeolian edge",
      "armor break",
      "avalanche axe",
      "blade: chi",
      "blade: jin",
      "blade: retsu",
      "blade: shun",
      "blade: yu",
      "blitz",
      "bora axe",
      "calamity",
      "circle blade",
      "combo",
      "crescent moon",
      "cyclone",
      "dagda",
      "dancing edge",
      "diarmuid",
      "disaster",
      "earth crusher",
      "exenterator",
      "expiacion",
      "fast blade",
      "fell cleave",
      "flat blade",
      "full swing",
      "hard slash",
      "heavy swing",
      "herculean slash",
      "howling fist",
      "iron tempest",
      "judgment",
      "king's justice",
      "leg sweep",
      "nightmare scythe",
      "numbing shot",
      "pyrrhic kleos",
      "raging axe",
      "raging fists",
      "raiden thrust",
      "rampage",
      "realmrazer",
      "requiescat",
      "resolution",
      "rock crusher",
      "ruthless stroke",
      "sarv",
      "savage blade",
      "seraph blade",
      "seraph strike",
      "shield break",
      "shining blade",
      "shining strike",
      "shoulder tackle",
      "sickle moon",
      "skewer",
      "slice",
      "smash axe",
      "sonic thrust",
      "spinning attack",
      "spinning axe",
      "spinning scythe",
      "spiral hell",
      "sturmwind",
      "tachi: ageha",
      "tachi: enpi",
      "tachi: goten",
      "tachi: jinpu",
      "tachi: koki",
      "thunder thrust",
      "tornado kick",
      "true strike",
      "trueflight",
      "viper bite",
      "vorpal blade",
      "vorpal scythe",
      "wasp sting",
      "weapon break",
    },
    groupings = {
      {
        open_with = {
          "aeolian edge",
          "armor break",
          "avalanche axe",
          "blade: chi",
          "blade: jin",
          "blade: retsu",
          "blade: shun",
          "blade: yu",
          "blitz",
          "bora axe",
          "calamity",
          "circle blade",
          "combo",
          "crescent moon",
          "cyclone",
          "dagda",
          "dancing edge",
          "diarmuid",
          "disaster",
          "earth crusher",
          "exenterator",
          "expiacion",
          "fast blade",
          "fell cleave",
          "flat blade",
          "full swing",
          "hard slash",
          "heavy swing",
          "herculean slash",
          "howling fist",
          "iron tempest",
          "judgment",
          "king's justice",
          "leg sweep",
          "nightmare scythe",
          "numbing shot",
          "pyrrhic kleos",
          "raging axe",
          "raging fists",
          "raiden thrust",
          "rampage",
          "realmrazer",
          "requiescat",
          "resolution",
          "rock crusher",
          "ruthless stroke",
          "sarv",
          "savage blade",
          "seraph blade",
          "seraph strike",
          "shield break",
          "shining blade",
          "shining strike",
          "shoulder tackle",
          "sickle moon",
          "skewer",
          "slice",
          "smash axe",
          "sonic thrust",
          "spinning attack",
          "spinning axe",
          "spinning scythe",
          "spiral hell",
          "sturmwind",
          "tachi: ageha",
          "tachi: enpi",
          "tachi: goten",
          "tachi: jinpu",
          "tachi: koki",
          "thunder thrust",
          "tornado kick",
          "true strike",
          "trueflight",
          "viper bite",
          "vorpal blade",
          "vorpal scythe",
          "wasp sting",
          "weapon break",
        },
        close_with = {
          "asuran fists",
          "blitz",
          "burning blade",
          "dulling arrow",
          "flaming arrow",
          "full swing",
          "red lotus blade",
          "ruthless stroke",
          "sniper shot",
          "spinning attack",
          "spinning axe",
          "stringing pummel",
          "tachi: kagero",
        },
      },
    },
  },
  ["reverberation"] = {
    all_openers = {
      "aeolian edge",
      "apex arrow",
      "ascetic's fury",
      "avalanche axe",
      "blade: chi",
      "blade: ku",
      "blade: retsu",
      "blade: rin",
      "blade: yu",
      "bora axe",
      "calamity",
      "crescent moon",
      "dagda",
      "dancing edge",
      "detonator",
      "diarmuid",
      "disaster",
      "double thrust",
      "drakesbane",
      "dulling arrow",
      "empyreal arrow",
      "evisceration",
      "exenterator",
      "expiacion",
      "fast blade",
      "fell cleave",
      "flaming arrow",
      "hard slash",
      "hot shot",
      "howling fist",
      "iron tempest",
      "king's justice",
      "leaden salute",
      "nightmare scythe",
      "omniscience",
      "piercing arrow",
      "power slash",
      "pyrrhic kleos",
      "raiden thrust",
      "rampage",
      "refulgent arrow",
      "requiescat",
      "resolution",
      "sarv",
      "savage blade",
      "seraph blade",
      "shining blade",
      "sickle moon",
      "sidewinder",
      "skewer",
      "slice",
      "slug shot",
      "sniper shot",
      "sonic thrust",
      "spinning axe",
      "spinning scythe",
      "spiral hell",
      "split shot",
      "stardiver",
      "sturmwind",
      "tachi: ageha",
      "tachi: enpi",
      "tachi: goten",
      "tachi: jinpu",
      "thunder thrust",
      "trueflight",
      "viper bite",
      "vorpal blade",
      "vorpal scythe",
      "vorpal thrust",
      "wasp sting",
    },
    groupings = {
      {
        open_with = {
          "aeolian edge",
          "ascetic's fury",
          "avalanche axe",
          "blade: chi",
          "blade: ku",
          "blade: retsu",
          "blade: rin",
          "bora axe",
          "calamity",
          "crescent moon",
          "dagda",
          "dancing edge",
          "detonator",
          "diarmuid",
          "disaster",
          "double thrust",
          "drakesbane",
          "dulling arrow",
          "empyreal arrow",
          "evisceration",
          "fast blade",
          "fell cleave",
          "flaming arrow",
          "hard slash",
          "howling fist",
          "iron tempest",
          "leaden salute",
          "nightmare scythe",
          "omniscience",
          "power slash",
          "raiden thrust",
          "rampage",
          "requiescat",
          "sarv",
          "seraph blade",
          "shining blade",
          "sickle moon",
          "skewer",
          "slice",
          "sniper shot",
          "sonic thrust",
          "spinning axe",
          "stardiver",
          "tachi: ageha",
          "tachi: enpi",
          "tachi: goten",
          "tachi: jinpu",
          "thunder thrust",
          "viper bite",
          "vorpal blade",
          "vorpal scythe",
          "wasp sting",
        },
        close_with = {
          "atonement",
          "blade: teki",
          "blade: yu",
          "brainshaker",
          "cataclysm",
          "circle blade",
          "dark harvest",
          "decimation",
          "entropy",
          "flash nova",
          "garland of bliss",
          "hot shot",
          "infernal scythe",
          "last stand",
          "origin",
          "oshala",
          "piercing arrow",
          "primal rend",
          "raging rush",
          "refulgent arrow",
          "retribution",
          "shadow of death",
          "shadowstitch",
          "shijin spiral",
          "shockwave",
          "shoulder tackle",
          "sidewinder",
          "skullbreaker",
          "slug shot",
          "smash axe",
          "spinning scythe",
          "split shot",
          "starburst",
          "sturmwind",
          "sunburst",
          "tachi: gekko",
          "tachi: koki",
          "terminus",
          "vorpal thrust",
          "zesho meppo",
        },
      },
      {
        open_with = {
          "apex arrow",
          "blade: yu",
          "exenterator",
          "expiacion",
          "hot shot",
          "king's justice",
          "piercing arrow",
          "pyrrhic kleos",
          "refulgent arrow",
          "resolution",
          "savage blade",
          "sidewinder",
          "slug shot",
          "spinning scythe",
          "spiral hell",
          "split shot",
          "sturmwind",
          "trueflight",
          "vorpal thrust",
        },
        close_with = {
          "atonement",
          "blade: teki",
          "blade: yu",
          "brainshaker",
          "cataclysm",
          "dark harvest",
          "decimation",
          "entropy",
          "garland of bliss",
          "hot shot",
          "infernal scythe",
          "last stand",
          "piercing arrow",
          "primal rend",
          "refulgent arrow",
          "retribution",
          "shadowstitch",
          "shijin spiral",
          "shockwave",
          "sidewinder",
          "slug shot",
          "spinning scythe",
          "split shot",
          "starburst",
          "sturmwind",
          "sunburst",
          "tachi: gekko",
          "vorpal thrust",
        },
      },
    },
  },
  ["scission"] = {
    all_openers = {
      "aeolian edge",
      "asuran fists",
      "backhand blow",
      "blade: jin",
      "blade: to",
      "blitz",
      "bora axe",
      "burning blade",
      "cyclone",
      "dancing edge",
      "dulling arrow",
      "earth crusher",
      "fell cleave",
      "fimbulvetr",
      "flaming arrow",
      "freezebite",
      "full swing",
      "gale axe",
      "gust slash",
      "herculean slash",
      "imperator",
      "maru kala",
      "numbing shot",
      "raging axe",
      "red lotus blade",
      "ruinator",
      "ruthless stroke",
      "shell crusher",
      "sniper shot",
      "spinning attack",
      "spinning axe",
      "steel cyclone",
      "stringing pummel",
      "tachi: jinpu",
      "tachi: kagero",
      "tachi: mumei",
      "tachi: yukikaze",
      "tornado kick",
      "true strike",
    },
    groupings = {
      {
        open_with = {
          "aeolian edge",
          "asuran fists",
          "backhand blow",
          "blade: jin",
          "blade: to",
          "blitz",
          "bora axe",
          "burning blade",
          "cyclone",
          "dancing edge",
          "dulling arrow",
          "earth crusher",
          "fell cleave",
          "fimbulvetr",
          "flaming arrow",
          "freezebite",
          "full swing",
          "gale axe",
          "gust slash",
          "herculean slash",
          "imperator",
          "maru kala",
          "numbing shot",
          "raging axe",
          "red lotus blade",
          "ruinator",
          "ruthless stroke",
          "shell crusher",
          "sniper shot",
          "spinning attack",
          "spinning axe",
          "steel cyclone",
          "stringing pummel",
          "tachi: jinpu",
          "tachi: kagero",
          "tachi: mumei",
          "tachi: yukikaze",
          "tornado kick",
          "true strike",
        },
        close_with = {
          "aeolian edge",
          "avalanche axe",
          "blade: retsu",
          "blade: yu",
          "bora axe",
          "calamity",
          "crescent moon",
          "dagda",
          "dancing edge",
          "diarmuid",
          "disaster",
          "exenterator",
          "expiacion",
          "fast blade",
          "fell cleave",
          "hard slash",
          "iron tempest",
          "king's justice",
          "nightmare scythe",
          "pyrrhic kleos",
          "rampage",
          "requiescat",
          "resolution",
          "sarv",
          "savage blade",
          "seraph blade",
          "shining blade",
          "sickle moon",
          "slice",
          "sonic thrust",
          "spinning axe",
          "spinning scythe",
          "spiral hell",
          "sturmwind",
          "tachi: ageha",
          "tachi: enpi",
          "tachi: jinpu",
          "trueflight",
          "viper bite",
          "vorpal blade",
          "vorpal scythe",
          "wasp sting",
        },
      },
    },
  },
  ["transfixion"] = {
    all_openers = {
      "black halo",
      "blade: ei",
      "blade: kamu",
      "cataclysm",
      "fimbulvetr",
      "imperator",
      "infernal scythe",
      "insurgency",
      "keen edge",
      "mandalic stab",
      "maru kala",
      "nightmare scythe",
      "one inch punch",
      "penta thrust",
      "starburst",
      "sunburst",
      "tachi: ageha",
      "tachi: kasha",
      "tachi: mumei",
      "tachi: shoha",
      "upheaval",
    },
    groupings = {
      {
        open_with = {
          "black halo",
          "blade: ei",
          "blade: kamu",
          "cataclysm",
          "fimbulvetr",
          "imperator",
          "infernal scythe",
          "insurgency",
          "keen edge",
          "mandalic stab",
          "maru kala",
          "nightmare scythe",
          "one inch punch",
          "penta thrust",
          "starburst",
          "sunburst",
          "tachi: ageha",
          "tachi: kasha",
          "tachi: mumei",
          "tachi: shoha",
          "upheaval",
        },
        close_with = {
          "apex arrow",
          "ascetic's fury",
          "blade: chi",
          "blade: ku",
          "blade: rin",
          "blast arrow",
          "blast shot",
          "dagda",
          "detonator",
          "diarmuid",
          "disaster",
          "double thrust",
          "drakesbane",
          "dulling arrow",
          "empyreal arrow",
          "evisceration",
          "flaming arrow",
          "hot shot",
          "howling fist",
          "leaden salute",
          "omniscience",
          "piercing arrow",
          "power slash",
          "raiden thrust",
          "refulgent arrow",
          "sarv",
          "sidewinder",
          "skewer",
          "slug shot",
          "sniper shot",
          "sonic thrust",
          "split shot",
          "stardiver",
          "tachi: enpi",
          "tachi: goten",
          "thunder thrust",
          "vorpal scythe",
          "vorpal thrust",
        },
      },
    },
  },
  ["distortion"] = {
    all_openers = {
      "apex arrow",
      "ascetic's fury",
      "black halo",
      "blade: chi",
      "blade: kamu",
      "blade: ku",
      "blade: metsu",
      "blade: rin",
      "blast arrow",
      "blast shot",
      "blitz",
      "camlann's torment",
      "cloudsplitter",
      "coronach",
      "dagda",
      "death blossom",
      "detonator",
      "diarmuid",
      "dimidiation",
      "disaster",
      "double thrust",
      "dragon kick",
      "drakesbane",
      "empyreal arrow",
      "evisceration",
      "exenterator",
      "exudation",
      "ground strike",
      "hot shot",
      "howling fist",
      "king's justice",
      "leaden salute",
      "mordant rime",
      "omniscience",
      "piercing arrow",
      "power slash",
      "raiden thrust",
      "randgrith",
      "refulgent arrow",
      "resolution",
      "ruthless stroke",
      "sarv",
      "savage blade",
      "shark bite",
      "sidewinder",
      "skewer",
      "slug shot",
      "sonic thrust",
      "spinning slash",
      "split shot",
      "stardiver",
      "tachi: enpi",
      "tachi: goten",
      "tachi: kaiten",
      "tachi: shoha",
      "thunder thrust",
      "trueflight",
      "ukko's fury",
      "uriel blade",
      "victory smite",
      "vidohunir",
      "vorpal scythe",
      "vorpal thrust",
    },
    groupings = {
      {
        open_with = {
          "black halo",
          "blade: kamu",
          "blade: metsu",
          "blitz",
          "camlann's torment",
          "cloudsplitter",
          "coronach",
          "death blossom",
          "dimidiation",
          "dragon kick",
          "exenterator",
          "exudation",
          "ground strike",
          "king's justice",
          "mordant rime",
          "randgrith",
          "resolution",
          "ruthless stroke",
          "savage blade",
          "shark bite",
          "spinning slash",
          "tachi: kaiten",
          "tachi: shoha",
          "trueflight",
          "ukko's fury",
          "uriel blade",
          "victory smite",
          "vidohunir",
        },
        close_with = {
          "chant du cygne",
          "cross reaper",
          "death blossom",
          "dragon blow",
          "expiacion",
          "fimbulvetr",
          "full break",
          "gate of tartarus",
          "geirskogul",
          "ground strike",
          "imperator",
          "maru kala",
          "mordant rime",
          "namas arrow",
          "pyrrhic kleos",
          "quietus",
          "rudra's storm",
          "ruinator",
          "spiral hell",
          "steel cyclone",
          "tachi: fudo",
          "tachi: gekko",
          "tachi: mumei",
          "torcleaver",
          "vidohunir",
        },
      },
      {
        open_with = {
          "apex arrow",
          "ascetic's fury",
          "blade: chi",
          "blade: ku",
          "blade: rin",
          "blast arrow",
          "blast shot",
          "dagda",
          "detonator",
          "diarmuid",
          "disaster",
          "double thrust",
          "drakesbane",
          "empyreal arrow",
          "evisceration",
          "hot shot",
          "howling fist",
          "leaden salute",
          "omniscience",
          "piercing arrow",
          "power slash",
          "raiden thrust",
          "refulgent arrow",
          "sarv",
          "sidewinder",
          "skewer",
          "slug shot",
          "sonic thrust",
          "split shot",
          "stardiver",
          "tachi: enpi",
          "tachi: goten",
          "thunder thrust",
          "vorpal scythe",
          "vorpal thrust",
        },
        close_with = {
          "blade: retsu",
          "bora axe",
          "crescent moon",
          "dagda",
          "dancing edge",
          "diarmuid",
          "disaster",
          "exenterator",
          "expiacion",
          "fast blade",
          "fell cleave",
          "hard slash",
          "iron tempest",
          "king's justice",
          "pyrrhic kleos",
          "rampage",
          "requiescat",
          "resolution",
          "sarv",
          "savage blade",
          "seraph blade",
          "shining blade",
          "slice",
          "sonic thrust",
          "spiral hell",
          "tachi: enpi",
          "tachi: jinpu",
          "trueflight",
          "viper bite",
          "vorpal scythe",
          "wasp sting",
        },
      },
    },
  },
  ["fragmentation"] = {
    all_openers = {
      "asuran fists",
      "blade: hi",
      "blade: ku",
      "blade: ten",
      "blade: to",
      "blast arrow",
      "blast shot",
      "catastrophe",
      "dagda",
      "diarmuid",
      "disaster",
      "entropy",
      "evisceration",
      "flash nova",
      "freezebite",
      "frostbite",
      "guillotine",
      "herculean slash",
      "impulse drive",
      "leaden salute",
      "mercy stroke",
      "numbing shot",
      "omniscience",
      "onslaught",
      "origin",
      "oshala",
      "primal rend",
      "raging rush",
      "requiescat",
      "retribution",
      "sarv",
      "shadow of death",
      "shattersoul",
      "skullbreaker",
      "stardiver",
      "stringing pummel",
      "swift blade",
      "tachi: hobaku",
      "tachi: rana",
      "tachi: yukikaze",
      "terminus",
      "tornado kick",
      "wildfire",
      "zesho meppo",
    },
    groupings = {
      {
        open_with = {
          "blade: to",
          "blast arrow",
          "blast shot",
          "flash nova",
          "freezebite",
          "frostbite",
          "guillotine",
          "herculean slash",
          "impulse drive",
          "numbing shot",
          "origin",
          "oshala",
          "raging rush",
          "shadow of death",
          "shattersoul",
          "skullbreaker",
          "tachi: hobaku",
          "tachi: rana",
          "tachi: yukikaze",
          "terminus",
          "tornado kick",
          "zesho meppo",
        },
        close_with = {
          "apex arrow",
          "atonement",
          "black halo",
          "blade: kamu",
          "blade: metsu",
          "blade: teki",
          "blade: yu",
          "blitz",
          "brainshaker",
          "camlann's torment",
          "circle blade",
          "cloudsplitter",
          "coronach",
          "dark harvest",
          "death blossom",
          "decimation",
          "dimidiation",
          "dragon kick",
          "entropy",
          "exenterator",
          "exudation",
          "flash nova",
          "garland of bliss",
          "ground strike",
          "hot shot",
          "king's justice",
          "last stand",
          "mordant rime",
          "origin",
          "oshala",
          "piercing arrow",
          "primal rend",
          "raging rush",
          "randgrith",
          "refulgent arrow",
          "resolution",
          "retribution",
          "ruthless stroke",
          "savage blade",
          "shadow of death",
          "shadowstitch",
          "shark bite",
          "shijin spiral",
          "shockwave",
          "sidewinder",
          "skullbreaker",
          "slug shot",
          "spinning scythe",
          "spinning slash",
          "split shot",
          "sturmwind",
          "tachi: kaiten",
          "tachi: koki",
          "tachi: shoha",
          "terminus",
          "trueflight",
          "ukko's fury",
          "uriel blade",
          "victory smite",
          "vidohunir",
          "vorpal thrust",
          "zesho meppo",
        },
      },
      {
        open_with = {
          "asuran fists",
          "blade: hi",
          "blade: ku",
          "blade: ten",
          "catastrophe",
          "dagda",
          "diarmuid",
          "disaster",
          "entropy",
          "evisceration",
          "leaden salute",
          "mercy stroke",
          "omniscience",
          "onslaught",
          "primal rend",
          "requiescat",
          "retribution",
          "sarv",
          "stardiver",
          "stringing pummel",
          "swift blade",
          "wildfire",
        },
        close_with = {
          "apex arrow",
          "black halo",
          "blade: kamu",
          "blitz",
          "camlann's torment",
          "death blossom",
          "dimidiation",
          "dragon kick",
          "exenterator",
          "ground strike",
          "king's justice",
          "mordant rime",
          "randgrith",
          "resolution",
          "ruthless stroke",
          "savage blade",
          "shark bite",
          "spinning slash",
          "tachi: kaiten",
          "tachi: shoha",
          "trueflight",
          "ukko's fury",
          "uriel blade",
          "victory smite",
          "vidohunir",
        },
      },
    },
  },
  ["fusion"] = {
    all_openers = {
      "asuran fists",
      "blitz",
      "burning blade",
      "chant du cygne",
      "cross reaper",
      "dragon blow",
      "dulling arrow",
      "expiacion",
      "fimbulvetr",
      "flaming arrow",
      "full break",
      "full swing",
      "gate of tartarus",
      "geirskogul",
      "imperator",
      "maru kala",
      "namas arrow",
      "pyrrhic kleos",
      "quietus",
      "red lotus blade",
      "rudra's storm",
      "ruinator",
      "ruthless stroke",
      "sniper shot",
      "spinning attack",
      "spinning axe",
      "spiral hell",
      "steel cyclone",
      "stringing pummel",
      "tachi: fudo",
      "tachi: gekko",
      "tachi: kagero",
      "tachi: mumei",
      "torcleaver",
    },
    groupings = {
      {
        open_with = {
          "asuran fists",
          "blitz",
          "burning blade",
          "dulling arrow",
          "flaming arrow",
          "full swing",
          "red lotus blade",
          "ruthless stroke",
          "sniper shot",
          "spinning attack",
          "spinning axe",
          "stringing pummel",
          "tachi: kagero",
        },
        close_with = {
          "armor break",
          "blade: chi",
          "blade: jin",
          "blade: shun",
          "blitz",
          "circle blade",
          "combo",
          "cyclone",
          "earth crusher",
          "flat blade",
          "full swing",
          "heavy swing",
          "herculean slash",
          "howling fist",
          "judgment",
          "leg sweep",
          "numbing shot",
          "raging axe",
          "raging fists",
          "raiden thrust",
          "realmrazer",
          "rock crusher",
          "ruthless stroke",
          "seraph strike",
          "shield break",
          "shining strike",
          "shoulder tackle",
          "skewer",
          "smash axe",
          "spinning attack",
          "tachi: goten",
          "tachi: koki",
          "thunder thrust",
          "tornado kick",
          "true strike",
          "weapon break",
        },
      },
      {
        open_with = {
          "chant du cygne",
          "cross reaper",
          "dragon blow",
          "expiacion",
          "fimbulvetr",
          "full break",
          "gate of tartarus",
          "geirskogul",
          "imperator",
          "maru kala",
          "namas arrow",
          "pyrrhic kleos",
          "quietus",
          "rudra's storm",
          "ruinator",
          "spiral hell",
          "steel cyclone",
          "tachi: fudo",
          "tachi: gekko",
          "tachi: mumei",
          "torcleaver",
        },
        close_with = {
          "arching arrow",
          "ascetic's fury",
          "atonement",
          "blade: shun",
          "decimation",
          "detonator",
          "drakesbane",
          "empyreal arrow",
          "fast blade ii",
          "final heaven",
          "garland of bliss",
          "glory slash",
          "heavy shot",
          "hexa strike",
          "insurgency",
          "jishnu's radiance",
          "knights of round",
          "last stand",
          "mandalic stab",
          "metatron torment",
          "mistral axe",
          "origin",
          "oshala",
          "realmrazer",
          "scourge",
          "shijin spiral",
          "tachi: kasha",
          "tachi: suikawari",
          "terminus",
          "upheaval",
          "wheeling thrust",
          "zesho meppo",
        },
      },
    },
  },
  ["gravitation"] = {
    all_openers = {
      "aeolian edge",
      "arching arrow",
      "ascetic's fury",
      "atonement",
      "backhand blow",
      "blade: jin",
      "blade: shun",
      "bora axe",
      "cyclone",
      "dancing edge",
      "decimation",
      "detonator",
      "drakesbane",
      "earth crusher",
      "empyreal arrow",
      "fast blade ii",
      "fell cleave",
      "fimbulvetr",
      "final heaven",
      "gale axe",
      "garland of bliss",
      "glory slash",
      "gust slash",
      "heavy shot",
      "hexa strike",
      "imperator",
      "insurgency",
      "jishnu's radiance",
      "knights of round",
      "last stand",
      "mandalic stab",
      "maru kala",
      "metatron torment",
      "mistral axe",
      "origin",
      "oshala",
      "raging axe",
      "realmrazer",
      "red lotus blade",
      "ruinator",
      "scourge",
      "shell crusher",
      "shijin spiral",
      "steel cyclone",
      "tachi: jinpu",
      "tachi: kasha",
      "tachi: mumei",
      "tachi: suikawari",
      "terminus",
      "true strike",
      "upheaval",
      "wheeling thrust",
      "zesho meppo",
    },
    groupings = {
      {
        open_with = {
          "arching arrow",
          "ascetic's fury",
          "atonement",
          "blade: shun",
          "decimation",
          "detonator",
          "drakesbane",
          "empyreal arrow",
          "fast blade ii",
          "final heaven",
          "garland of bliss",
          "glory slash",
          "heavy shot",
          "hexa strike",
          "insurgency",
          "jishnu's radiance",
          "knights of round",
          "last stand",
          "mandalic stab",
          "metatron torment",
          "mistral axe",
          "origin",
          "oshala",
          "realmrazer",
          "scourge",
          "shijin spiral",
          "tachi: kasha",
          "tachi: suikawari",
          "terminus",
          "upheaval",
          "wheeling thrust",
          "zesho meppo",
        },
        close_with = {
          "asuran fists",
          "blade: hi",
          "blade: ku",
          "blade: ten",
          "catastrophe",
          "dagda",
          "diarmuid",
          "disaster",
          "entropy",
          "evisceration",
          "impulse drive",
          "leaden salute",
          "mercy stroke",
          "omniscience",
          "onslaught",
          "primal rend",
          "requiescat",
          "retribution",
          "sarv",
          "shattersoul",
          "stardiver",
          "stringing pummel",
          "swift blade",
          "tachi: rana",
          "wildfire",
        },
      },
      {
        open_with = {
          "aeolian edge",
          "backhand blow",
          "blade: jin",
          "bora axe",
          "cyclone",
          "dancing edge",
          "earth crusher",
          "fell cleave",
          "fimbulvetr",
          "gale axe",
          "gust slash",
          "imperator",
          "maru kala",
          "raging axe",
          "red lotus blade",
          "shell crusher",
          "tachi: jinpu",
          "tachi: mumei",
          "true strike",
        },
        close_with = {
          "black halo",
          "blade: ei",
          "blade: kamu",
          "insurgency",
          "keen edge",
          "mandalic stab",
          "nightmare scythe",
          "one inch punch",
          "penta thrust",
          "tachi: ageha",
          "tachi: kasha",
          "tachi: shoha",
          "upheaval",
        },
      },
      {
        open_with = {
          "ruinator",
          "steel cyclone",
        },
        close_with = {
          "black halo",
          "blade: ei",
          "blade: kamu",
          "cataclysm",
          "fimbulvetr",
          "imperator",
          "infernal scythe",
          "keen edge",
          "maru kala",
          "nightmare scythe",
          "one inch punch",
          "penta thrust",
          "starburst",
          "sunburst",
          "tachi: ageha",
          "tachi: mumei",
          "tachi: shoha",
        },
      },
    },
  },
  ["darkness"] = {
    all_openers = {
      "asuran fists",
      "blade: hi",
      "blade: ku",
      "blade: ten",
      "catastrophe",
      "chant du cygne",
      "cross reaper",
      "dagda",
      "death blossom",
      "diarmuid",
      "disaster",
      "dragon blow",
      "entropy",
      "evisceration",
      "expiacion",
      "fimbulvetr",
      "full break",
      "gate of tartarus",
      "geirskogul",
      "ground strike",
      "imperator",
      "impulse drive",
      "leaden salute",
      "maru kala",
      "mercy stroke",
      "mordant rime",
      "namas arrow",
      "omniscience",
      "onslaught",
      "primal rend",
      "pyrrhic kleos",
      "quietus",
      "requiescat",
      "retribution",
      "rudra's storm",
      "ruinator",
      "sarv",
      "shattersoul",
      "spiral hell",
      "stardiver",
      "steel cyclone",
      "stringing pummel",
      "swift blade",
      "tachi: fudo",
      "tachi: gekko",
      "tachi: mumei",
      "tachi: rana",
      "torcleaver",
      "vidohunir",
      "wildfire",
    },
    groupings = {
      {
        open_with = {
          "asuran fists",
          "blade: hi",
          "blade: ku",
          "blade: ten",
          "catastrophe",
          "dagda",
          "diarmuid",
          "disaster",
          "entropy",
          "evisceration",
          "impulse drive",
          "leaden salute",
          "mercy stroke",
          "omniscience",
          "onslaught",
          "primal rend",
          "requiescat",
          "retribution",
          "sarv",
          "shattersoul",
          "stardiver",
          "stringing pummel",
          "swift blade",
          "tachi: rana",
          "wildfire",
        },
        close_with = {
          "chant du cygne",
          "cross reaper",
          "dragon blow",
          "expiacion",
          "fimbulvetr",
          "full break",
          "geirskogul",
          "imperator",
          "maru kala",
          "namas arrow",
          "pyrrhic kleos",
          "ruinator",
          "spiral hell",
          "steel cyclone",
          "tachi: fudo",
          "tachi: gekko",
          "tachi: mumei",
          "torcleaver",
        },
      },
      {
        open_with = {
          "chant du cygne",
          "cross reaper",
          "death blossom",
          "dragon blow",
          "expiacion",
          "fimbulvetr",
          "full break",
          "geirskogul",
          "ground strike",
          "imperator",
          "maru kala",
          "mordant rime",
          "namas arrow",
          "pyrrhic kleos",
          "ruinator",
          "spiral hell",
          "steel cyclone",
          "tachi: fudo",
          "tachi: gekko",
          "tachi: mumei",
          "torcleaver",
          "vidohunir",
        },
        close_with = {
          "asuran fists",
          "blade: hi",
          "blade: ku",
          "blade: ten",
          "catastrophe",
          "dagda",
          "diarmuid",
          "disaster",
          "entropy",
          "evisceration",
          "impulse drive",
          "leaden salute",
          "mercy stroke",
          "omniscience",
          "onslaught",
          "primal rend",
          "requiescat",
          "retribution",
          "sarv",
          "shattersoul",
          "stardiver",
          "stringing pummel",
          "swift blade",
          "tachi: rana",
          "wildfire",
        },
      },
      {
        open_with = {
          "gate of tartarus",
          "quietus",
          "rudra's storm",
        },
        close_with = {
          "asuran fists",
          "blade: ku",
          "blade: ten",
          "dagda",
          "diarmuid",
          "disaster",
          "entropy",
          "evisceration",
          "impulse drive",
          "leaden salute",
          "omniscience",
          "primal rend",
          "requiescat",
          "retribution",
          "sarv",
          "shattersoul",
          "stardiver",
          "stringing pummel",
          "swift blade",
          "tachi: rana",
        },
      },
    },
  },
  ["light"] = {
    all_openers = {
      "apex arrow",
      "arching arrow",
      "ascetic's fury",
      "atonement",
      "black halo",
      "blade: kamu",
      "blade: metsu",
      "blade: shun",
      "blitz",
      "camlann's torment",
      "cloudsplitter",
      "coronach",
      "death blossom",
      "decimation",
      "detonator",
      "dimidiation",
      "dragon kick",
      "drakesbane",
      "empyreal arrow",
      "exenterator",
      "exudation",
      "fast blade ii",
      "final heaven",
      "garland of bliss",
      "glory slash",
      "ground strike",
      "heavy shot",
      "hexa strike",
      "insurgency",
      "jishnu's radiance",
      "king's justice",
      "knights of round",
      "last stand",
      "mandalic stab",
      "metatron torment",
      "mistral axe",
      "mordant rime",
      "origin",
      "oshala",
      "randgrith",
      "realmrazer",
      "resolution",
      "ruthless stroke",
      "savage blade",
      "scourge",
      "shark bite",
      "shijin spiral",
      "spinning slash",
      "tachi: kaiten",
      "tachi: kasha",
      "tachi: shoha",
      "tachi: suikawari",
      "terminus",
      "trueflight",
      "ukko's fury",
      "upheaval",
      "uriel blade",
      "victory smite",
      "vidohunir",
      "wheeling thrust",
      "zesho meppo",
    },
    groupings = {
      {
        open_with = {
          "arching arrow",
          "ascetic's fury",
          "atonement",
          "blade: shun",
          "decimation",
          "detonator",
          "drakesbane",
          "empyreal arrow",
          "fast blade ii",
          "final heaven",
          "garland of bliss",
          "glory slash",
          "heavy shot",
          "hexa strike",
          "insurgency",
          "jishnu's radiance",
          "knights of round",
          "last stand",
          "mandalic stab",
          "metatron torment",
          "mistral axe",
          "origin",
          "oshala",
          "realmrazer",
          "scourge",
          "shijin spiral",
          "tachi: kasha",
          "tachi: suikawari",
          "terminus",
          "upheaval",
          "wheeling thrust",
          "zesho meppo",
        },
        close_with = {
          "apex arrow",
          "black halo",
          "blade: kamu",
          "blade: metsu",
          "blitz",
          "cloudsplitter",
          "coronach",
          "death blossom",
          "dragon kick",
          "exenterator",
          "exudation",
          "ground strike",
          "king's justice",
          "mordant rime",
          "resolution",
          "ruthless stroke",
          "savage blade",
          "shark bite",
          "spinning slash",
          "tachi: shoha",
          "trueflight",
          "vidohunir",
        },
      },
      {
        open_with = {
          "apex arrow",
          "black halo",
          "blade: kamu",
          "blade: metsu",
          "blitz",
          "camlann's torment",
          "cloudsplitter",
          "coronach",
          "death blossom",
          "dimidiation",
          "dragon kick",
          "exenterator",
          "exudation",
          "ground strike",
          "king's justice",
          "mordant rime",
          "randgrith",
          "resolution",
          "ruthless stroke",
          "savage blade",
          "shark bite",
          "spinning slash",
          "tachi: kaiten",
          "tachi: shoha",
          "trueflight",
          "ukko's fury",
          "uriel blade",
          "victory smite",
          "vidohunir",
        },
        close_with = {
          "arching arrow",
          "ascetic's fury",
          "atonement",
          "blade: shun",
          "decimation",
          "detonator",
          "drakesbane",
          "empyreal arrow",
          "fast blade ii",
          "garland of bliss",
          "heavy shot",
          "hexa strike",
          "insurgency",
          "last stand",
          "mandalic stab",
          "mistral axe",
          "origin",
          "oshala",
          "realmrazer",
          "shijin spiral",
          "tachi: kasha",
          "tachi: suikawari",
          "terminus",
          "upheaval",
          "wheeling thrust",
          "zesho meppo",
        },
      },
    },
  },
  ["darkness ii"] = {
    all_openers = {
      "blade: hi",
      "blade: metsu",
      "catastrophe",
      "cloudsplitter",
      "coronach",
      "exudation",
      "gate of tartarus",
      "mercy stroke",
      "onslaught",
      "quietus",
      "rudra's storm",
      "wildfire",
    },
    groupings = {
      {
        open_with = {
          "blade: hi",
          "blade: metsu",
          "catastrophe",
          "cloudsplitter",
          "coronach",
          "exudation",
          "gate of tartarus",
          "mercy stroke",
          "onslaught",
          "quietus",
          "rudra's storm",
          "wildfire",
        },
        close_with = {
          "blade: hi",
          "blade: metsu",
          "catastrophe",
          "cloudsplitter",
          "coronach",
          "exudation",
          "gate of tartarus",
          "mercy stroke",
          "onslaught",
          "quietus",
          "rudra's storm",
          "wildfire",
        },
      },
    },
  },
  ["light ii"] = {
    all_openers = {
      "camlann's torment",
      "chant du cygne",
      "dimidiation",
      "final heaven",
      "final paradise",
      "geirskogul",
      "glory slash",
      "jishnu's radiance",
      "knights of rotund",
      "knights of round",
      "metatron torment",
      "namas arrow",
      "randgrith",
      "scourge",
      "tachi: fudo",
      "tachi: kaiten",
      "torcleaver",
      "ukko's fury",
      "uriel blade",
      "victory smite",
    },
    groupings = {
      {
        open_with = {
          "camlann's torment",
          "chant du cygne",
          "dimidiation",
          "final heaven",
          "final paradise",
          "geirskogul",
          "glory slash",
          "jishnu's radiance",
          "knights of rotund",
          "knights of round",
          "metatron torment",
          "namas arrow",
          "randgrith",
          "scourge",
          "tachi: fudo",
          "tachi: kaiten",
          "torcleaver",
          "ukko's fury",
          "uriel blade",
          "victory smite",
        },
        close_with = {
          "camlann's torment",
          "chant du cygne",
          "dimidiation",
          "final heaven",
          "final paradise",
          "geirskogul",
          "glory slash",
          "jishnu's radiance",
          "knights of rotund",
          "knights of round",
          "metatron torment",
          "namas arrow",
          "randgrith",
          "scourge",
          "tachi: fudo",
          "tachi: kaiten",
          "torcleaver",
          "ukko's fury",
          "uriel blade",
          "victory smite",
        },
      },
    },
  },
}
