-- Automatically generated file: Trust Metadata

return {
  [896] = {id=896,name="Shantotto",en="Shantotto",ja="シャントット",party_name="Shantotto",model=3000,main_job="BLM",main_job_id=4,sub_job="BLM",sub_job_id=4},
  [897] = {id=897,name="Naji",en="Naji",ja="ナジ",party_name="Naji",model=3001,main_job="WAR",main_job_id=1,sub_job="WAR",sub_job_id=1},
  [898] = {id=898,name="Kupipi",en="Kupipi",ja="クピピ",party_name="Kupipi",model=3002,main_job="WHM",main_job_id=3,sub_job="WHM",sub_job_id=3},
  [899] = {id=899,name="Excenmille",en="Excenmille",ja="エグセニミル",party_name="Excenmille",model=3003,main_job="PLD",main_job_id=7,sub_job="PLD",sub_job_id=7},
  [900] = {id=900,name="Ayame",en="Ayame",ja="アヤメ",party_name="Ayame",model=3004,main_job="SAM",main_job_id=12,sub_job="SAM",sub_job_id=12},
  [901] = {id=901,name="Nanaa Mihgo",en="Nanaa Mihgo",ja="ナナー・ミーゴ",party_name="NanaaMihgo",model=3005,main_job="THF",main_job_id=6,sub_job="THF",sub_job_id=6},
  [902] = {id=902,name="Curilla",en="Curilla",ja="クリルラ",party_name="Curilla",model=3006,main_job="PLD",main_job_id=7,sub_job="PLD",sub_job_id=7},
  [903] = {id=903,name="Volker",en="Volker",ja="フォルカー",party_name="Volker",model=3007,main_job="WAR",main_job_id=1,sub_job="WAR",sub_job_id=1},
  [904] = {id=904,name="Ajido-Marujido",en="Ajido-Marujido",ja="アジドマルジド",party_name="Ajido-Marujido",model=3008,main_job="BLM",main_job_id=4,sub_job="RDM",sub_job_id=5},
  [905] = {id=905,name="Trion",en="Trion",ja="トリオン",party_name="Trion",model=3009,main_job="PLD",main_job_id=7,sub_job="WAR",sub_job_id=1},
  [906] = {id=906,name="Zeid",en="Zeid",ja="ザイド",party_name="Zeid",model=3010,main_job="DRK",main_job_id=8,sub_job="DRK",sub_job_id=8},
  [907] = {id=907,name="Lion",en="Lion",ja="ライオン",party_name="Lion",model=3011,main_job="THF",main_job_id=6,sub_job="THF",sub_job_id=6},
  [908] = {id=908,name="Tenzen",en="Tenzen",ja="テンゼン",party_name="Tenzen",model=3012,main_job="SAM",main_job_id=12,sub_job="SAM",sub_job_id=12},
  [909] = {id=909,name="Mihli Aliapoh",en="Mihli Aliapoh",ja="ミリ・アリアポー",party_name="MihliAliapoh",model=3013,main_job="WHM",main_job_id=3,sub_job="WHM",sub_job_id=3},
  [910] = {id=910,name="Valaineral",en="Valaineral",ja="ヴァレンラール",party_name="Valaineral",model=3014,main_job="PLD",main_job_id=7,sub_job="WAR",sub_job_id=1},
  [911] = {id=911,name="Joachim",en="Joachim",ja="ヨアヒム",party_name="Joachim",model=3015,main_job="BRD",main_job_id=10,sub_job="WHM",sub_job_id=3},
  [912] = {id=912,name="Naja Salaheem",en="Naja Salaheem",ja="ナジャ・サラヒム",party_name="NajaSalaheem",model=3016,main_job="MNK",main_job_id=2,sub_job="WAR",sub_job_id=1},
  [913] = {id=913,name="Prishe",en="Prishe",ja="プリッシュ",party_name="Prishe",model=3017,main_job="MNK",main_job_id=2,sub_job="WHM",sub_job_id=3},
  [914] = {id=914,name="Ulmia",en="Ulmia",ja="ウルミア",party_name="Ulmia",model=3018,main_job="BRD",main_job_id=10,sub_job="BRD",sub_job_id=10},
  [915] = {id=915,name="Shikaree Z",en="Shikaree Z",ja="スカリーZ",party_name="ShikareeZ",model=3019,main_job="DRG",main_job_id=14,sub_job="WHM",sub_job_id=3},
  [916] = {id=916,name="Cherukiki",en="Cherukiki",ja="チェルキキ",party_name="Cherukiki",model=3020,main_job="WHM",main_job_id=3,sub_job="BLM",sub_job_id=4},
  [917] = {id=917,name="Iron Eater",en="Iron Eater",ja="アイアンイーター",party_name="IronEater",model=3021,main_job="WAR",main_job_id=1,sub_job="WAR",sub_job_id=1},
  [918] = {id=918,name="Gessho",en="Gessho",ja="ゲッショー",party_name="Gessho",model=3022,main_job="NIN",main_job_id=13,sub_job="WAR",sub_job_id=1},
  [919] = {id=919,name="Gadalar",en="Gadalar",ja="ガダラル",party_name="Gadalar",model=3023,main_job="BLM",main_job_id=4,sub_job="BLM",sub_job_id=4},
  [920] = {id=920,name="Rainemard",en="Rainemard",ja="ライニマード",party_name="Rainemard",model=3024,main_job="RDM",main_job_id=5,sub_job="PLD",sub_job_id=7},
  [921] = {id=921,name="Ingrid",en="Ingrid",ja="イングリッド",party_name="Ingrid",model=3025,main_job="WHM",main_job_id=3,sub_job="WHM",sub_job_id=3},
  [922] = {id=922,name="Lehko Habhoka",en="Lehko Habhoka",ja="レコ・ハボッカ",party_name="LehkoHabhoka",model=3026,main_job="THF",main_job_id=6,sub_job="BLM",sub_job_id=4},
  [923] = {id=923,name="Nashmeira",en="Nashmeira",ja="ナシュメラ",party_name="Nashmeira",model=3027,main_job="PUP",main_job_id=18,sub_job="WHM",sub_job_id=3},
  [924] = {id=924,name="Zazarg",en="Zazarg",ja="ザザーグ",party_name="Zazarg",model=3028,main_job="MNK",main_job_id=2,sub_job="MNK",sub_job_id=2},
  [925] = {id=925,name="Ovjang",en="Ovjang",ja="アヴゼン",party_name="Ovjang",model=3029,main_job="RDM",main_job_id=5,sub_job="BLM",sub_job_id=4},
  [926] = {id=926,name="Mnejing",en="Mnejing",ja="メネジン",party_name="Mnejing",model=3030,main_job="PLD",main_job_id=7,sub_job="PLD",sub_job_id=7},
  [927] = {id=927,name="Sakura",en="Sakura",ja="サクラ",party_name="Sakura",model=3031,main_job="GEO",main_job_id=21,sub_job="BRD",sub_job_id=10,non_interactive=true},
  [928] = {id=928,name="Luzaf",en="Luzaf",ja="ルザフ",party_name="Luzaf",model=3032,main_job="COR",main_job_id=17,sub_job="NIN",sub_job_id=13},
  [929] = {id=929,name="Najelith",en="Najelith",ja="ナジュリス",party_name="Najelith",model=3033,main_job="RNG",main_job_id=11,sub_job="RNG",sub_job_id=11},
  [930] = {id=930,name="Aldo",en="Aldo",ja="アルド",party_name="Aldo",model=3034,main_job="THF",main_job_id=6,sub_job="NIN",sub_job_id=13},
  [931] = {id=931,name="Moogle",en="Moogle",ja="モーグリ",party_name="Moogle",model=3035,main_job="GEO",main_job_id=21,sub_job="BRD",sub_job_id=10,non_interactive=true},
  [932] = {id=932,name="Fablinix",en="Fablinix",ja="ファブリニクス",party_name="Fablinix",model=3036,main_job="THF",main_job_id=6,sub_job="RDM",sub_job_id=5},
  [933] = {id=933,name="Maat",en="Maat",ja="マート",party_name="Maat",model=3037,main_job="MNK",main_job_id=2,sub_job="THF",sub_job_id=6},
  [934] = {id=934,name="D. Shantotto",en="D. Shantotto",ja="D.シャントット",party_name="D.Shantotto",model=3038,main_job="BLM",main_job_id=4,sub_job="DRK",sub_job_id=8},
  [935] = {id=935,name="Star Sibyl",en="Star Sibyl",ja="星の神子",party_name="StarSibyl",model=3039,main_job="GEO",main_job_id=21,sub_job="BRD",sub_job_id=10,non_interactive=true},
  [936] = {id=936,name="Karaha-Baruha",en="Karaha-Baruha",ja="カラハバルハ",party_name="Karaha-Baruha",model=3040,main_job="WHM",main_job_id=3,sub_job="SMN",sub_job_id=15},
  [937] = {id=937,name="Cid",en="Cid",ja="シド",party_name="Cid",model=3041,main_job="WAR",main_job_id=1,sub_job="RNG",sub_job_id=11},
  [938] = {id=938,name="Gilgamesh",en="Gilgamesh",ja="ギルガメッシュ",party_name="Gilgamesh",model=3042,main_job="SAM",main_job_id=12,sub_job="WAR",sub_job_id=1},
  [939] = {id=939,name="Areuhat",en="Areuhat",ja="アレヴァト",party_name="Areuhat",model=3043,main_job="WAR",main_job_id=1,sub_job="PLD",sub_job_id=7},
  [940] = {id=940,name="Semih Lafihna",en="Semih Lafihna",ja="セミ・ラフィーナ",party_name="SemihLafihna",model=3044,main_job="RNG",main_job_id=11,sub_job="WAR",sub_job_id=1},
  [941] = {id=941,name="Elivira",en="Elivira",ja="エリヴィラ",party_name="Elivira",model=3045,main_job="RNG",main_job_id=11,sub_job="WAR",sub_job_id=1},
  [942] = {id=942,name="Noillurie",en="Noillurie",ja="ノユリ",party_name="Noillurie",model=3046,main_job="SAM",main_job_id=12,sub_job="PLD",sub_job_id=7},
  [943] = {id=943,name="Lhu Mhakaracca",en="Lhu Mhakaracca",ja="ルー・マカラッカ",party_name="LhuMhakaracca",model=3047,main_job="BST",main_job_id=9,sub_job="WAR",sub_job_id=1},
  [944] = {id=944,name="Ferreous Coffin",en="Ferreous Coffin",ja="フェリアスコフィン",party_name="FerreousCoffin",model=3048,main_job="WHM",main_job_id=3,sub_job="WAR",sub_job_id=1},
  [945] = {id=945,name="Lilisette",en="Lilisette",ja="リリゼット",party_name="Lilisette",model=3049,main_job="DNC",main_job_id=19,sub_job="DNC",sub_job_id=19},
  [946] = {id=946,name="Mumor",en="Mumor",ja="ミュモル",party_name="Mumor",model=3050,main_job="DNC",main_job_id=19,sub_job="WAR",sub_job_id=1},
  [947] = {id=947,name="Uka Totlihn",en="Uka Totlihn",ja="ウカ・トトゥリン",party_name="UkaTotlihn",model=3051,main_job="DNC",main_job_id=19,sub_job="WAR",sub_job_id=1},
  [948] = {id=948,name="Klara",en="Klara",ja="クララ",party_name="Klara",model=3053,main_job="WAR",main_job_id=1,sub_job="WAR",sub_job_id=1},
  [949] = {id=949,name="Romaa Mihgo",en="Romaa Mihgo",ja="ロマー・ミーゴ",party_name="RomaaMihgo",model=3054,main_job="THF",main_job_id=6,sub_job="WAR",sub_job_id=1},
  [950] = {id=950,name="Kuyin Hathdenna",en="Kuyin Hathdenna",ja="クイン・ハスデンナ",party_name="KuyinHathdenna",model=3055,main_job="GEO",main_job_id=21,sub_job="BRD",sub_job_id=10,non_interactive=true},
  [951] = {id=951,name="Rahal",en="Rahal",ja="ラーアル",party_name="Rahal",model=3056,main_job="PLD",main_job_id=7,sub_job="WAR",sub_job_id=1},
  [952] = {id=952,name="Koru-Moru",en="Koru-Moru",ja="コルモル",party_name="Koru-Moru",model=3057,main_job="RDM",main_job_id=5,sub_job="WHM",sub_job_id=3},
  [953] = {id=953,name="Pieuje (UC)",en="Pieuje (UC)",ja="ピエージェ(UC)",party_name="Pieuje",model=3058,main_job="WHM",main_job_id=3,sub_job="PLD",sub_job_id=7},
  [954] = {id=954,name="I. Shield (UC)",en="I. Shield (UC)",ja="I.シールド(UC)",party_name="InvincibleShld",model=3060,main_job="WAR",main_job_id=1,sub_job="COR",sub_job_id=17},
  [955] = {id=955,name="Apururu (UC)",en="Apururu (UC)",ja="アプルル(UC)",party_name="Apururu",model=3061,main_job="WHM",main_job_id=3,sub_job="RDM",sub_job_id=5},
  [956] = {id=956,name="Jakoh (UC)",en="Jakoh (UC)",ja="ジャコ(UC)",party_name="JakohWahcondalo",model=3062,main_job="THF",main_job_id=6,sub_job="WAR",sub_job_id=1},
  [957] = {id=957,name="Flaviria (UC)",en="Flaviria (UC)",ja="フラヴィリア(UC)",party_name="Flaviria",model=3059,main_job="DRG",main_job_id=14,sub_job="WAR",sub_job_id=1},
  [958] = {id=958,name="Babban",en="Babban",ja="ウェイレア",party_name="Babban",model=3067,main_job="MNK",main_job_id=2,sub_job="MNK",sub_job_id=2},
  [959] = {id=959,name="Abenzio",en="Abenzio",ja="アベンツィオ",party_name="Abenzio",model=3068,main_job="MNK",main_job_id=2,sub_job="WAR",sub_job_id=1},
  [960] = {id=960,name="Rughadjeen",en="Rughadjeen",ja="ルガジーン",party_name="Rughadjeen",model=3069,main_job="PLD",main_job_id=7,sub_job="PLD",sub_job_id=7},
  [961] = {id=961,name="Kukki-Chebukki",en="Kukki-Chebukki",ja="クッキーチェブキー",party_name="Kukki-Chebukki",model=3070,main_job="BLM",main_job_id=4,sub_job="BLM",sub_job_id=4},
  [962] = {id=962,name="Margret",en="Margret",ja="マルグレート",party_name="Margret",model=3071,main_job="RNG",main_job_id=11,sub_job="THF",sub_job_id=6},
  [963] = {id=963,name="Chacharoon",en="Chacharoon",ja="チャチャルン",party_name="Chacharoon",model=3072,main_job="THF",main_job_id=6,sub_job="RNG",sub_job_id=11},
  [964] = {id=964,name="Lhe Lhangavo",en="Lhe Lhangavo",ja="レイ・ランガヴォ",party_name="LheLhangavo",model=3073,main_job="MNK",main_job_id=2,sub_job="WAR",sub_job_id=1},
  [965] = {id=965,name="Arciela",en="Arciela",ja="アシェラ",party_name="Arciela",model=3074,main_job="RDM",main_job_id=5,sub_job="PLD",sub_job_id=7},
  [966] = {id=966,name="Mayakov",en="Mayakov",ja="マヤコフ",party_name="Mayakov",model=3075,main_job="DNC",main_job_id=19,sub_job="WAR",sub_job_id=1},
  [967] = {id=967,name="Qultada",en="Qultada",ja="クルタダ",party_name="Qultada",model=3076,main_job="COR",main_job_id=17,sub_job="RNG",sub_job_id=11},
  [968] = {id=968,name="Adelheid",en="Adelheid",ja="アーデルハイト",party_name="Adelheid",model=3077,main_job="SCH",main_job_id=20,sub_job="BLM",sub_job_id=4},
  [969] = {id=969,name="Amchuchu",en="Amchuchu",ja="アムチュチュ",party_name="Amchuchu",model=3078,main_job="RUN",main_job_id=22,sub_job="WAR",sub_job_id=1},
  [970] = {id=970,name="Brygid",en="Brygid",ja="ブリジッド",party_name="Brygid",model=3079,main_job="GEO",main_job_id=21,sub_job="BRD",sub_job_id=10,non_interactive=true},
  [971] = {id=971,name="Mildaurion",en="Mildaurion",ja="ミルドリオン",party_name="Mildaurion",model=3080,main_job="PLD",main_job_id=7,sub_job="SAM",sub_job_id=12},
  [972] = {id=972,name="Halver",en="Halver",ja="ハルヴァー",party_name="Halver",model=3087,main_job="PLD",main_job_id=7,sub_job="WAR",sub_job_id=1},
  [973] = {id=973,name="Rongelouts",en="Rongelouts",ja="ロンジェルツ",party_name="Rongelouts",model=3088,main_job="WAR",main_job_id=1,sub_job="WAR",sub_job_id=1},
  [974] = {id=974,name="Leonoyne",en="Leonoyne",ja="レオノアーヌ",party_name="Leonoyne",model=3089,main_job="BLM",main_job_id=4,sub_job="PLD",sub_job_id=7},
  [975] = {id=975,name="Maximilian",en="Maximilian",ja="マクシミリアン",party_name="Maximilian",model=3090,main_job="THF",main_job_id=6,sub_job="NIN",sub_job_id=13},
  [976] = {id=976,name="Kayeel-Payeel",en="Kayeel-Payeel",ja="カイルパイル",party_name="Kayeel-Payeel",model=3091,main_job="BLM",main_job_id=4,sub_job="SMN",sub_job_id=15},
  [977] = {id=977,name="Robel-Akbel",en="Robel-Akbel",ja="ロベルアクベル",party_name="Robel-Akbel",model=3092,main_job="BLM",main_job_id=4,sub_job="SMN",sub_job_id=15},
  [978] = {id=978,name="Kupofried",en="Kupofried",ja="クポフリート",party_name="Kupofried",model=3093,main_job="GEO",main_job_id=21,sub_job="BRD",sub_job_id=10,non_interactive=true},
  [979] = {id=979,name="Selh'teus",en="Selh'teus",ja="セルテウス",party_name="Selh'teus",model=3094,main_job="PLD",main_job_id=7,sub_job="SAM",sub_job_id=12},
  [980] = {id=980,name="Yoran-Oran (UC)",en="Yoran-Oran (UC)",ja="ヨランオラン(UC)",party_name="Yoran-Oran",model=3095,main_job="WHM",main_job_id=3,sub_job="BLM",sub_job_id=4},
  [981] = {id=981,name="Sylvie (UC)",en="Sylvie (UC)",ja="シルヴィ(UC)",party_name="Sylvie",model=3096,main_job="GEO",main_job_id=21,sub_job="WHM",sub_job_id=3},
  [982] = {id=982,name="Abquhbah",en="Abquhbah",ja="アブクーバ",party_name="Abquhbah",model=3098,main_job="WAR",main_job_id=1,sub_job="MNK",sub_job_id=2},
  [983] = {id=983,name="Balamor",en="Balamor",ja="バラモア",party_name="Balamor",model=3099,main_job="DRK",main_job_id=8,sub_job="BLM",sub_job_id=4},
  [984] = {id=984,name="August",en="August",ja="オーグスト",party_name="August",model=3100,main_job="PLD",main_job_id=7,sub_job="WAR",sub_job_id=1},
  [985] = {id=985,name="Rosulatia",en="Rosulatia",ja="ロスレーシャ",party_name="Rosulatia",model=3101,main_job="BLM",main_job_id=4,sub_job="DRK",sub_job_id=8},
  [986] = {id=986,name="Teodor",en="Teodor",ja="テオドール",party_name="Teodor",model=3103,main_job="BLM",main_job_id=4,sub_job="DRK",sub_job_id=8},
  [987] = {id=987,name="Ullegore",en="Ullegore",ja="ウルゴア",party_name="Ullegore",model=3105,main_job="BLM",main_job_id=4,sub_job="DRK",sub_job_id=8},
  [988] = {id=988,name="Makki-Chebukki",en="Makki-Chebukki",ja="マッキーチェブキー",party_name="Makki-Chebukki",model=3106,main_job="RNG",main_job_id=11,sub_job="BLM",sub_job_id=4},
  [989] = {id=989,name="King of Hearts",en="King of Hearts",ja="キング・オブ・ハーツ",party_name="KingOfHearts",model=3107,main_job="RDM",main_job_id=5,sub_job="WHM",sub_job_id=3},
  [990] = {id=990,name="Morimar",en="Morimar",ja="モリマー",party_name="Morimar",model=3108,main_job="BST",main_job_id=9,sub_job="WAR",sub_job_id=1},
  [991] = {id=991,name="Darrcuiln",en="Darrcuiln",ja="ダラクァルン",party_name="Darrcuiln",model=3109,main_job="WAR",main_job_id=1,sub_job="RDM",sub_job_id=5},
  [992] = {id=992,name="AAHM",en="AAHM",ja="アークHM",party_name="ArkHM",model=3113,main_job="NIN",main_job_id=13,sub_job="WAR",sub_job_id=1},
  [993] = {id=993,name="AAEV",en="AAEV",ja="アークEV",party_name="ArkEV",model=3114,main_job="PLD",main_job_id=7,sub_job="WHM",sub_job_id=3},
  [994] = {id=994,name="AAMR",en="AAMR",ja="アークMR",party_name="ArkMR",model=3115,main_job="BST",main_job_id=9,sub_job="THF",sub_job_id=6},
  [995] = {id=995,name="AATT",en="AATT",ja="アークTT",party_name="ArkTT",model=3116,main_job="BLM",main_job_id=4,sub_job="DRK",sub_job_id=8},
  [996] = {id=996,name="AAGK",en="AAGK",ja="アークGK",party_name="ArkGK",model=3117,main_job="SAM",main_job_id=12,sub_job="DRG",sub_job_id=14},
  [997] = {id=997,name="Iroha",en="Iroha",ja="イロハ",party_name="Iroha",model=3111,main_job="SAM",main_job_id=12,sub_job="WHM",sub_job_id=3},
  [998] = {id=998,name="Ygnas",en="Ygnas",ja="ユグナス",party_name="Ygnas",model=3118,main_job="WHM",main_job_id=3,sub_job="PLD",sub_job_id=7},
  [999] = {id=999,name="Monberaux",en="Monberaux",ja="モンブロー",party_name="Monberaux",model=3120,main_job="PLD",main_job_id=7,sub_job="RUN",sub_job_id=22},
  [1002] = {id=1002,name="Cornelia",en="Cornelia",ja="コーネリア",party_name="Cornelia",model=3119,main_job="GEO",main_job_id=21,sub_job="BRD",sub_job_id=10,non_interactive=true},
  [1003] = {id=1003,name="Matsui-P",en="Matsui-P",ja="マツイP",party_name="Matsui-P",model=3121,main_job="NIN",main_job_id=13,sub_job="BLM",sub_job_id=4},
  [1004] = {id=1004,name="Excenmille [S]",en="Excenmille [S]",ja="エグセニミルII",party_name="Excenmille",model=3052,main_job="WAR",main_job_id=1,sub_job="PLD",sub_job_id=7},
  [1005] = {id=1005,name="Ayame (UC)",en="Ayame (UC)",ja="アヤメ(UC)",party_name="Ayame",model=3063,main_job="SAM",main_job_id=12,sub_job="WAR",sub_job_id=1},
  [1006] = {id=1006,name="Maat (UC)",en="Maat (UC)",ja="マート(UC)",party_name="Maat",model=3064,main_job="MNK",main_job_id=2,sub_job="WAR",sub_job_id=1},
  [1007] = {id=1007,name="Aldo (UC)",en="Aldo (UC)",ja="アルド(UC)",party_name="Aldo",model=3065,main_job="THF",main_job_id=6,sub_job="NIN",sub_job_id=13},
  [1008] = {id=1008,name="Naja (UC)",en="Naja (UC)",ja="ナジャ(UC)",party_name="NajaSalaheem",model=3066,main_job="MNK",main_job_id=2,sub_job="WAR",sub_job_id=1},
  [1009] = {id=1009,name="Lion II",en="Lion II",ja="ライオンII",party_name="Lion",model=3081,main_job="THF",main_job_id=6,sub_job="NIN",sub_job_id=13},
  [1010] = {id=1010,name="Zeid II",en="Zeid II",ja="ザイドII",party_name="Zeid",model=3086,main_job="DRK",main_job_id=8,sub_job="WAR",sub_job_id=1},
  [1011] = {id=1011,name="Prishe II",en="Prishe II",ja="プリッシュII",party_name="Prishe",model=3082,main_job="WHM",main_job_id=3,sub_job="MNK",sub_job_id=2},
  [1012] = {id=1012,name="Nashmeira II",en="Nashmeira II",ja="ナシュメラII",party_name="Nashmeira",model=3083,main_job="WHM",main_job_id=3,sub_job="PUP",sub_job_id=18},
  [1013] = {id=1013,name="Lilisette II",en="Lilisette II",ja="リリゼットII",party_name="Lilisette",model=3084,main_job="DNC",main_job_id=19,sub_job="WAR",sub_job_id=1},
  [1014] = {id=1014,name="Tenzen II",en="Tenzen II",ja="テンゼンII",party_name="Tenzen",model=3097,main_job="SAM",main_job_id=12,sub_job="RNG",sub_job_id=11},
  [1015] = {id=1015,name="Mumor II",en="Mumor II",ja="ミュモルII",party_name="Mumor",model=3104,main_job="BLM",main_job_id=4,sub_job="DNC",sub_job_id=19},
  [1016] = {id=1016,name="Ingrid II",en="Ingrid II",ja="イングリッドII",party_name="Ingrid",model=3102,main_job="WHM",main_job_id=3,sub_job="WAR",sub_job_id=1},
  [1017] = {id=1017,name="Arciela II",en="Arciela II",ja="アシェラII",party_name="Arciela",model=3085,main_job="RDM",main_job_id=5,sub_job="BLM",sub_job_id=4},
  [1018] = {id=1018,name="Iroha II",en="Iroha II",ja="イロハII",party_name="Iroha",model=3112,main_job="SAM",main_job_id=12,sub_job="WHM",sub_job_id=3},
  [1019] = {id=1019,name="Shantotto II",en="Shantotto II",ja="シャントットII",party_name="Shantotto",model=3110,main_job="BLM",main_job_id=4,sub_job="WHM",sub_job_id=3}
}, {"id", "name", "en", "ja", "party_name", "model", "main_job", "main_job_id", "sub_job", "sub_job_id", "non_interactive"}

--[[
Copyright ©2024 Kaiconure@Github

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
]]
